homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'firetv'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    media_player.master_bedroom_fire_tv:
      <<: *customize
      friendly_name: "Fire TV - Master Bedroom"
      icon: mdi:television
    
