homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'opensky'

    automation.flight_enter_home_region:
      <<: *customize
      friendly_name: "OpenSky: Flight Entered Home Region"

    automation.flight_exit_home_region:
      <<: *customize
      friendly_name: "OpenSky: Flight Exited Home Region"

    automation.ghettobird_overhead:
      <<: *customize
      friendly_name: "OpenSky: Ghettobird Overhead"
      ghettobird_callsigns: "N145DV, N5185G, N530JL, N911BL, N911WY"

    automation.ghettobird_gone:
      <<: *customize
      friendly_name: "OpenSky: Ghettobird Left"

    input_boolean.ghettobird_overhead:
      <<: *customize
      hidden: true

    binary_sensor.ghettobird_overhead:
      <<: *customize
      friendly_name: "Ghettobird Overhead"
      icon: mdi:helicopter

input_boolean:
  ghettobird_overhead:
    icon: mdi:helicopter

binary_sensor:
  - platform: template
    sensors:
      ghettobird_overhead:
        value_template: "{{ is_state('input_boolean.ghettobird_overhead','on') }}"
        device_class: occupancy
        delay_on: 00:00:30

automation:
  - alias: 'flight_enter_home_region'
    trigger:
      platform: event
      event_type: opensky_entry
      event_data:
        sensor: sky_at_home
    action:
      service: notify.flight_alerts
      data_template:
        message : 'Flight entry of {{ trigger.event.data.callsign }} (https://www.flightradar24.com/{{ trigger.event.data.callsign }}/)'

  - alias: 'flight_exit_home_region'
    trigger:
      platform: event
      event_type: opensky_exit
      event_data:
        sensor: sky_at_home
    action:
      service: notify.flight_alerts
      data_template:
        message : 'Flight exit of {{ trigger.event.data.callsign }} '

  - alias: 'ghettobird_overhead'
    trigger:
      platform: event
      event_type: opensky_entry
      event_data:
        sensor: sky_at_home
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.callsign in state_attr('automation.ghettobird_overhead','ghettobird_callsigns') }}"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.ghettobird_overhead

  - alias: 'ghettobird_gone'
    trigger:
      platform: event
      event_type: opensky_exit
      event_data:
        sensor: sky_at_home
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.callsign in state_attr('automation.ghettobird_overhead','ghettobird_callsigns') }}"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.ghettobird_overhead