sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    scan_interval: '00:05:00'
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - alerts
      - temperature
      - precip_type
      - precip_probability
      - wind_speed
      - wind_gust
      - wind_bearing
      - cloud_cover
      - humidity
      - temperature_high
      - temperature_low
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily