homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'freenas'
      freenas_rest_sensor: &freenas_rest_sensor
        username: !secret freenas_username
        password: !secret freenas_password
        authentication: basic
        headers:
          Content-Type: application/json
    
    sensor.freenas_tank_report:
      <<: *customize
      friendly_name: FreeNAS - Volume Status - Tank
      
    sensor.freenas_tank_pct_used:
      <<: *customize
      friendly_name: FreeNAS - Volume % Free - Tank
      
    sensor.freenas_alert_level:
      <<: *customize
      friendly_name: FreeNAS - Alert Level
      
    sensor.freenas_alert_message:
      <<: *customize
      friendly_name: FreeNAS - Alert Message
      
    sensor.freenas_version:
      <<: *customize
      friendly_name: FreeNAS - Version
      
    sensor.freenas_resilver_time_remaining:
      <<: *customize
      
    sensor.freenas_resilver_etc:
      <<: *customize
      friendly_name: FreeNAS - Resilver Estimated Time To Completion
      
sensor:
  - platform: rest
    <<: *freenas_rest_sensor
    name: freenas_tank_report
    json_attributes:
      - name
      - status
      - used_pct
      - is_decrypted
    resource: http://freenas.twohunnid/api/v1.0/storage/volume/tank/?format=json
    value_template: '{{ value_json.status }}'
      
  - platform: rest
    <<: *freenas_rest_sensor
    name: freenas_all_alerts
    resource: http://freenas.twohunnid/api/v1.0/system/alert/?format=json
    value_template: >
      {{ value_json.objects | length }}
    json_attributes:
      - objects
    
  - platform: rest
    <<: *freenas_rest_sensor
    name: freenas_version
    json_attributes:
      - fullversion
      - name
      - version
    resource: http://freenas.twohunnid/api/v1.0/system/version/?format=json
    value_template: '{{ value_json.fullversion }}'

  - platform: rest
    <<: *freenas_rest_sensor
    method: POST
    resource: http://freenas.twohunnid/api/v2.0/disk/temperatures
    payload: '{"names":["ada0", "ada1", "ada2", "ada3"],"powermode":"NEVER"}'
    name: freenas_disk_temps
    json_attributes:
      - ada0
      - ada1
      - ada2
      - ada3

  - platform: template
    sensors:
      freenas_tank_pct_used:
        value_template: "{{ state_attr('sensor.freenas_tank_report','used_pct').title() }}"
        entity_id: sensor.freenas_tank_report
      freenas_resilver_etc:
        value_template: '{{ (now().strftime("%s") | int(default=0) + (states("sensor.freenas_resilver_time_remaining") | int(default=0))) | timestamp_custom("%m/%d/%y %H:%M") }}'
        entity_id: sensor.freenas_resilver_time_remaining
      freenas_active_alerts:
        value_template: >
          {{ state_attr('sensor.freenas_all_alerts','objects') | rejectattr('dismissed') | list | length }}
        attribute_templates:
          alerts: "{{ state_attr('sensor.freenas_all_alerts','objects') | rejectattr('dismissed') | sort(attribute='timestamp',reverse=True) | list }}"
      freenas_alert_level:
        value_template: "{{ (state_attr('sensor.freenas_active_alerts','alerts') | list | first).level }}"
        attribute_templates:
          message: "{{ (state_attr('sensor.freenas_active_alerts','alerts') | list | first).message }}"
          timestamp: "{{ (state_attr('sensor.freenas_active_alerts','alerts') | list | first).timestamp }}"
          level: "{{ (state_attr('sensor.freenas_active_alerts','alerts') | list | first).level }}"
      freenas_alert_message:
        entity_id: sensor.freenas_alert_level
        value_template: "{{ state_attr('sensor.freenas_alert_level','message') }}"
      freenas_disk_temp_ada0:
        unit_of_measurement: 'C째'
        value_template: "{{ state_attr('sensor.freenas_disk_temps','ada0') }}"
      freenas_disk_temp_ada1:
        unit_of_measurement: 'C째'
        value_template: "{{ state_attr('sensor.freenas_disk_temps','ada1') }}"
      freenas_disk_temp_ada2:
        unit_of_measurement: 'C째'
        value_template: "{{ state_attr('sensor.freenas_disk_temps','ada2') }}"
      freenas_disk_temp_ada3:
        unit_of_measurement: 'C째'
        value_template: "{{ state_attr('sensor.freenas_disk_temps','ada3') }}"