homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'homeassistant_hardware'
        
    sensor.disk_use_percent_home:
      <<: *customize
      
    sensor.memory_use_percent:
      <<: *customize
      
    sensor.load_5m:
      <<: *customize
      
    sensor.last_boot:
      <<: *customize