homeassistant:  
  telegram_bot:
    - platform: webhooks
      api_key: !secret telegram_bot_key
      parse_mode: html
      trusted_networks:
        - 149.154.167.197/32
        - 149.154.167.198/31
        - 149.154.167.200/29
        - 149.154.167.208/28
        - 149.154.167.224/29
        - 149.154.167.232/31
        - !secret http_reverse_proxy_ip
      allowed_chat_ids:
        - !secret telegram_bot_chat_id_1
        
notify:
  - name: !secret telegram_bot_chat_name_1
    platform: telegram
    chat_id: !secret telegram_bot_chat_id_1
  - name: telegram
    platform: group
    services:
      - service: !secret telegram_bot_chat_name_1