homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'govee_leak_detectors'
        
    binary_sensor.govee_leak_detector_27124:
      <<: *customize
      friendly_name: "Leak Sensor - North Water Heater"

    binary_sensor.govee_leak_detector_27124_button:
      <<: *customize
      friendly_name: "Leak Sensor Button - North Water Heater"

    binary_sensor.govee_leak_detector_23480:
      <<: *customize
      friendly_name: "Leak Sensor - South Water Heater"

    binary_sensor.govee_leak_detector_23480_button:
      <<: *customize
      friendly_name: "Leak Sensor Button - South Water Heater"

    binary_sensor.govee_leak_detector_25410:
      <<: *customize
      friendly_name: "Leak Sensor - Kitchen"

    binary_sensor.govee_leak_detector_25410_button:
      <<: *customize
      friendly_name: "Leak Sensor Button - Kitchen"

    binary_sensor.govee_leak_detector_28624:
      <<: *customize
      friendly_name: "Leak Sensor - Laundry"

    binary_sensor.govee_leak_detector_28624_button:
      <<: *customize
      friendly_name: "Leak Sensor Button - Laundry"

    binary_sensor.govee_leak_detector_26832:
      <<: *customize
      friendly_name: "Leak Sensor - Master Bath"

    binary_sensor.govee_leak_detector_26832_button:
      <<: *customize
      friendly_name: "Leak Sensor Button - Master Bath"

    binary_sensor.govee_leak_detector_2186:
      <<: *customize
      friendly_name: "Leak Sensor - Library Bath"

    binary_sensor.govee_leak_detector_2186_button:
      <<: *customize
      friendly_name: "Leak Sensor Button - Library Bath"

    binary_sensor.govee_leak_detector_2842:
      <<: *customize
      friendly_name: "Leak Sensor - Spare Bath"

    binary_sensor.govee_leak_detector_2842_button:
      <<: *customize
      friendly_name: "Leak Sensor Button - Spare Bath"

mqtt:
  binary_sensor:
    - name: govee_leak_detector_27124
      payload_on: "Water Leak"
      off_delay: 10
      device_class: moisture
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/27124/event"
    - name: govee_leak_detector_27124_button
      payload_on: "Button Press"
      off_delay: 10
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/27124/event"
      
    - name: govee_leak_detector_23480
      payload_on: "Water Leak"
      off_delay: 10
      device_class: moisture
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/23480/event"
    - name: govee_leak_detector_23480_button
      payload_on: "Button Press"
      off_delay: 10
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/23480/event"
      
    - name: govee_leak_detector_25410
      payload_on: "Water Leak"
      off_delay: 10
      device_class: moisture
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/25410/event"
    - name: govee_leak_detector_25410_button
      payload_on: "Button Press"
      off_delay: 10
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/25410/event"
      
    - name: govee_leak_detector_28624
      payload_on: "Water Leak"
      off_delay: 10
      device_class: moisture
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/28624/event"
    - name: govee_leak_detector_28624_button
      payload_on: "Button Press"
      off_delay: 10
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/28624/event"
      
    - name: govee_leak_detector_26832
      payload_on: "Water Leak"
      off_delay: 10
      device_class: moisture
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/26832/event"
    - name: govee_leak_detector_26832_button
      payload_on: "Button Press"
      off_delay: 10
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/26832/event"
      
    - name: govee_leak_detector_2186
      payload_on: "Water Leak"
      off_delay: 10
      device_class: moisture
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/2186/event"
    - name: govee_leak_detector_2186_button
      payload_on: "Button Press"
      off_delay: 10
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/2186/event"
      
    - name: govee_leak_detector_2842
      payload_on: "Water Leak"
      off_delay: 10
      device_class: moisture
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/2842/event"
    - name: govee_leak_detector_2842_button
      payload_on: "Button Press"
      off_delay: 10
      state_topic: "rtl_433/iwatchtheplants/devices/Govee-Water/2842/event"
