################################################################
## Packages / Halloween Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'halloween_mode'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Input Boolean
    ################################################
    
    input_boolean.halloween_mode:
      <<: *customize
      friendly_name: "Halloween Mode?"
      icon: mdi:halloween
      persistent: true

################################################
## Input Boolean
################################################

input_boolean:
  halloween_mode:
    initial: off
    
script:
  halloween_front_porch_cycle_step_1:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "milight/0xFD01/rgb_cct/0"
          payload: '{"status": "ON", "brightness":10, "transition": 1}'
      - service: script.porch_lights_transition_left
        data:
          color: '{"r": 255, "g": 52, "b": 0}'
          transition: 1
      - service: script.porch_lights_transition_right
        data:
          color: '{"r": 204, "g": 0, "b": 204}'
          transition: 1
      - delay: '00:00:13'
      - condition: state
        entity_id: light.front_porch_lights
        state: 'on'
      - service: script.halloween_front_porch_cycle_step_2
  halloween_front_porch_cycle_step_2:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "milight/0xFD01/rgb_cct/0"
          payload: '{"status": "ON", "brightness":10, "transition": 1}'
      - service: script.porch_lights_transition_left
        data:
          color: '{"r": 204, "g": 0, "b": 204}'
          transition: 1
      - service: script.porch_lights_transition_right
        data:
          color: '{"r": 255, "g": 52, "b": 0}'
          transition: 1
      - delay: '00:00:13'
      - condition: state
        entity_id: light.front_porch_lights
        state: 'on'
      - service: script.halloween_front_porch_cycle_step_1