################################################################
## Packages / Halloween Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'halloween_mode'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Input Boolean
    ################################################
    
    input_boolean.halloween_mode:
      <<: *customize
      friendly_name: "Halloween Mode?"
      icon: mdi:halloween
      persistent: true
      
    automation.halloween_mode_front_porch_cycle_on:
      <<: *customize
      friendly_name: "Halloween Mode: Cycle Front Porch Lights"

################################################
## Input Boolean
################################################

input_boolean:
  halloween_mode:
    initial: off
    
group:
  halloween_automations:
    name: Halloween Automations
    entities: 
    - automation.halloween_mode_front_porch_cycle_on
    
automation:
  - id: enable_halloween_automations
    alias: Enable Halloween Automations when Halloween Mode On
    trigger:
    - platform: state
      entity_id: input_boolean.halloween_mode
      to: 'on'
    condition: []
    action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.halloween_automations
        
  - id: disable_halloween_automations
    alias: Disable Halloween Automations when Halloween Mode Off
    trigger:
    - platform: state
      entity_id: input_boolean.halloween_mode
      to: 'off'
    condition: []
    action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.halloween_automations
        
  - alias: halloween_mode_front_porch_cycle_on
    trigger:
      platform: state
      entity_id: switch.front_porch_lights
      from: 'off'
      to: 'on'
    action:
      - service: script.turn_off
        data:
          entity_id: script.halloween_front_porch_cycle_step_1
    
script:
  halloween_front_porch_cycle_step_1:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "milight/0xFD01/rgb_cct/0"
          payload: '{"status": "ON", "brightness":10, "transition": 1}'
      - delay: '00:00:01'
      - service: script.porch_lights_transition_left
        data:
          color: '{"r": 255, "g": 52, "b": 0}'
          transition: 1
      - service: script.porch_lights_transition_right
        data:
          color: '{"r": 204, "g": 0, "b": 204}'
          transition: 1
      - delay: '00:00:13'
      - condition: state
        entity_id: light.front_porch_lights
        state: 'on'
      - service: script.halloween_front_porch_cycle_step_2
  halloween_front_porch_cycle_step_2:
    sequence:
      - service: mqtt.publish
        data_template:
          topic: "milight/0xFD01/rgb_cct/0"
          payload: '{"status": "ON", "brightness":10, "transition": 1}'
      - delay: '00:00:01'
      - service: script.porch_lights_transition_left
        data:
          color: '{"r": 204, "g": 0, "b": 204}'
          transition: 1
      - service: script.porch_lights_transition_right
        data:
          color: '{"r": 255, "g": 52, "b": 0}'
          transition: 1
      - delay: '00:00:13'
      - condition: state
        entity_id: light.front_porch_lights
        state: 'on'
      - service: script.halloween_front_porch_cycle_step_1