homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'motion_detection_alerts'
        
    automation.motion_detected_interior:
      <<: *customize
        
    automation.motion_detected_exterior:
      <<: *customize
      
    automation.reactivate_exterior_motion_detection_alerts_after_30_minutes:
      <<: *customize
      
    automation.reactivate_interior_motion_detection_alerts_after_30_minutes:
      <<: *customize
      
    automation.telegram_command_snooze_all_exterior_motion_sensors_alerts:
      <<: *customize
      
    automation.telegram_command_snooze_all_interior_motion_sensors_alerts:
      <<: *customize
        
    script.motion_detection_alert:
      <<: *customize
        
    script.motion_detection_alert_camera:
      <<: *customize
      
    script.snooze_interior_detection_alerts:
      <<: *customize
      
    script.snooze_exterior_detection_alerts:
      <<: *customize

automation:

  - alias: 'Motion Detected: Interior'
    trigger:
    - entity_id: 
      - binary_sensor.piper_sensor_motion
      - binary_sensor.motion_indoor_foyer
      - binary_sensor.garage_camera_motion
      - binary_sensor.modetftp_motion_laundry
      - binary_sensor.ballet_studio_camera_motion_sensor_debounced
      - binary_sensor.living_room_camera_motion_sensor_debounced
      from: 'off'
      platform: state
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_night
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
    - service: script.turn_on
      data_template:
        entity_id: &script_entity_id >
          script.motion_detection_alert{% if 'camera_entity_id' in trigger.to_state.attributes %}_camera{% endif  %}
        variables:
          camera_entity_id: "{{ trigger.to_state.attributes.camera_entity_id }}"
          motion_group: "group.all_interior_motion_sensors"
          
  - alias: 'Motion Detected: Exterior'
    trigger:
    - entity_id: 
        - binary_sensor.motion_backyard_north
        - binary_sensor.backyard_patio_camera_motion
        - binary_sensor.motion_backyard_south
        - binary_sensor.motion_front_yard_south
        - binary_sensor.motion_front_driveway
        - binary_sensor.front_door_camera_motion_detected
        - binary_sensor.front_yard_camera_motion
      from: 'off'
      platform: state
      to: 'on'
    condition: []
    action:
    - service: script.turn_on
      data_template:
        entity_id: *script_entity_id 
        variables:
          camera_entity_id: "{{ trigger.to_state.attributes.camera_entity_id }}"
          motion_group: "group.all_exterior_motion_sensors"
          
  - alias: 'Reactivate Exterior Motion Detection Alerts After 30 minutes'
    trigger:
    - platform: state
      entity_id:
        - automation.motion_detected_exterior
      to: 'off'
      for: '00:30:00'
    condition: []
    action:
      - service: homeassistant.turn_on
        entity_id: automation.motion_detected_exterior
      - service: homeassistant.turn_off
        entity_id: automation.reactivate_exterior_motion_detection_alerts_after_30_minutes
          
  - alias: 'Reactivate Interior Motion Detection Alerts After 30 minutes'
    trigger:
    - platform: state
      entity_id:
        - automation.motion_detected_interior
      to: 'off'
      for: '00:30:00'
    condition: []
    action:
      - service: homeassistant.turn_on
        entity_id: automation.motion_detected_interior
      - service: homeassistant.turn_off
        entity_id: automation.reactivate_interior_motion_detection_alerts_after_30_minutes
        
  - alias: 'Telegram Command: snooze_all_exterior_motion_sensors_alerts'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/snooze_all_exterior_motion_sensors_alerts'
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'OK!'
      - service: homeassistant.turn_on
        entity_id: script.snooze_exterior_detection_alerts
        
  - alias: 'Telegram Command: snooze_all_interior_motion_sensors_alerts'
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/snooze_all_interior_motion_sensors_alerts'
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'OK!'
      - service: homeassistant.turn_on
        entity_id: script.snooze_interior_detection_alerts
     
    
          
          
script:

  snooze_interior_detection_alerts:
    alias: Snooze Interior Detection Alerts for 30 minutes
    sequence:
      - service: notify.nick
        data_template:
          message: "Interior motion detection alerts have been snoozed for 30 minutes."
      - service: homeassistant.turn_on
        entity_id: automation.reactivate_interior_motion_detection_alerts_after_30_minutes
      - service: homeassistant.turn_off
        entity_id: automation.motion_detected_interior

  snooze_exterior_detection_alerts:
    alias: Snooze Exterior Detection Alerts for 30 minutes
    sequence:
      - service: notify.nick
        data_template:
          message: "Exterior motion detection alerts have been snoozed for 30 minutes."
      - service: homeassistant.turn_on
        entity_id: automation.reactivate_exterior_motion_detection_alerts_after_30_minutes
      - service: homeassistant.turn_off
        entity_id: automation.motion_detected_exterior

  snooze_all_detection_alerts:
    alias: Snooze All Detection Alerts for 30 minutes
    sequence:
      - service: homeassistant.turn_on
        entity_id: script.snooze_exterior_detection_alerts
      - service: homeassistant.turn_on
        entity_id: script.snooze_interior_detection_alerts

  motion_detection_alert:
    alias: Motion Detection Alert
    sequence:
    - service: notify.nick
      data_template:
        message: &motion_detected_message >
          Motion detected: {{ state_attr(motion_group,'friendly_name')|replace('Motion Sensors - ','') }}
          {% for obj in states|sort(attribute='last_updated',reverse=1) if obj.entity_id in state_attr(motion_group,'entity_id') and obj.state == 'on' %}{{ obj.attributes.friendly_name|replace('Motion - ','') }} ({{ (now() - obj.last_updated).total_seconds()|int }}s ago){% if loop.index < loop.length %}, {% endif %}{% endfor %}
        data:
          inline_keyboard: 
            - "Snooze?:/snooze_{{motion_group|replace('group.','')}}_alerts"
             
  motion_detection_alert_camera:
    alias: Motion Detection Alert (from Camera)
    sequence:
    - service: camera.snapshot
      data_template:
        entity_id: "camera.{{ camera_entity_id }}"
        filename: "/tmp/{{ camera_entity_id }}_snapshot.jpg"
    - service: notify.nick
      data_template:
        message: *motion_detected_message
        data:
          photo:
            caption: *motion_detected_message
            file: "/tmp/{{ camera_entity_id }}_snapshot.jpg"
          inline_keyboard: 
            - "Snooze?:/snooze_{{motion_group|replace('group.','')}}_alerts"