- id: '1534899458430'
  alias: 'Exterior Lights: On at Dusk'
  trigger:
  - event: sunset
    offset: -00:10
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.exterior_landscape_lights
    service: homeassistant.turn_on
- id: '1534899747739'
  alias: 'Exterior Lights: Off at 10pm'
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_off
- id: '1537420454578'
  alias: 'HAStatus: Shutdown'
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: brb
    service: notify.nick
- id: '1537420502502'
  alias: 'HAStatus: Start'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: back
    service: notify.nick
- id: '1537936842222'
  alias: 'Alarm State: Armed, Run "Alarm State: Armed (Any)" Script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_night
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_home
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_away
  condition: []
  action:
  - service: script.alarm_state_armed_any
- id: '1537938020420'
  alias: 'Alarm State: Disarmed, run Disarmed script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: disarmed
  condition: []
  action:
  - service: script.alarm_state_disarmed
- id: '1538007620959'
  alias: 'Alarm State: Armed Night, run "Armed Night" script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_night
  condition: []
  action:
  - service: script.alarm_state_armed_night
- id: '1538111242565'
  alias: 'Security: Doop Doop when backyard motion and armed night'
  trigger:
  - entity_id: group.motion_backyard
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_night
  - condition: state
    entity_id: group.motion_front_yard
    state: 'on'
  action:
  - service: script.siren_beep_beep
- id: backyard_flood_lights_on_when_back_door_unlocked
  alias: 'Backyard Floodlights On When Back Door Unlocked '
  trigger:
  - entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: light.backyard_flood_lights
    state: 'off'
  - after: sunset
    after_offset: 00:30:00
    condition: sun
  action:
  - data:
      entity_id: light.backyard_flood_lights
    service: homeassistant.turn_on
- id: backyard_flood_lights_off_when_back_door_locked
  alias: 'Backyard Floodlights Off When Back Door Locked '
  trigger:
  - entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
    from: unlocked
    platform: state
    to: locked
  condition:
  - condition: state
    entity_id: light.backyard_flood_lights
    state: 'on'
  - after: sunset
    after_offset: 00:30:00
    condition: sun
  action:
  - data:
      entity_id: light.backyard_flood_lights
    service: homeassistant.turn_off
- id: '1547347950847'
  alias: Zwift Level Up
  trigger:
  - entity_id: sensor.zwift_level_803962
    platform: state
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state | int > trigger.from_state.state |
      int }}'
  action:
  - data:
      message: congrats on your zwift level!
    service: notify.nick
- id: '1550015887078'
  alias: 'Nick gets Home by car/bike: Activate Scene'
  trigger:
  - entity_id: input_boolean.presence_nick_homekit
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - above: '7'
    condition: numeric_state
    entity_id: sensor.velocity_nick
  action:
  - scene: scene.nick_gets_home
- id: '1551828897602'
  alias: HA Server Overload
  trigger:
  - above: '2'
    entity_id: sensor.load_5m
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Homeassistant load has been over 2.00 for the 5m average... might want
        to look into it
    service: notify.nick
- id: '1558144520212'
  alias: turn off pool lights when you turn them on
  trigger:
  - entity_id: light.pool_light
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.pool_light
    service: light.turn_off
- id: '1561093920492'
  alias: flood lights off automatically
  trigger:
  - entity_id: light.backyard_flood_lights
    platform: state
    to: 'on'
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.backyard_flood_lights
- id: '1564508234534'
  alias: 'Pool Pump : On in the morning'
  trigger:
  - at: '8:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.pool_pump
    service: switch.turn_on
- id: '1564508283934'
  alias: 'Pool Pump: Off at night'
  trigger:
  - at: '19:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.pool_pump
    service: switch.turn_off
- id: '1567051911910'
  alias: Pantry Light Off After 3 Mins
  trigger:
  - entity_id: light.pantry_light
    for: 00:03:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.pantry_light
    service: light.turn_off
- id: '1573699277520'
  alias: Garage Lights Off After 2.5 Mins No Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.garage_camera_motion
    for: 00:02:30
    platform: state
    to: 'off'
  - entity_id: light.garage_overhead_light
    for: 00:02:30
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.garage_camera_motion
    state: 'off'
  action:
  - data:
      entity_id: light.garage_overhead_light
    service: light.turn_off
- id: '1573699279520'
  alias: Ballet Studio Lights Off After 5 Mins No Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.ballet_studio_camera_motion_sensor_debounced
    for: 00:05:00
    platform: state
    to: 'off'
  - entity_id: light.z_wave_products_inc_wd100_level_3
    for: 00:05:00
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.ballet_studio_camera_motion_sensor_debounced
    state: 'off'
  action:
  - data:
      entity_id: light.z_wave_products_inc_wd100_level_3
    service: light.turn_off
- id: '1573699508759'
  alias: Garage Lights On If Doors Open After Dusk
  description: ''
  trigger:
  - above: '0'
    entity_id: sensor.garage_door_position
    for: 00:00:01
    platform: numeric_state
  - entity_id: binary_sensor.garage_interior_door
    platform: state
    to: 'on'
  condition:
  - after: '16:00:00'
    before: '6:00:00'
    condition: time
  action:
  - data:
      entity_id: light.garage_overhead_light
    service: homeassistant.turn_on
- id: '1580193218706'
  alias: Plant room lights on at sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: light.z_wave_products_inc_wd100_level_2
    service: light.turn_on
- id: '1580193276234'
  alias: Plant room lights off at sundown
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: light.z_wave_products_inc_wd100_level_2
    service: light.turn_off
- id: '1581130104525'
  alias: Ballet studio lights on when motion detected at night
  description: ''
  trigger:
  - entity_id: binary_sensor.ballet_studio_camera_motion_sensor_debounced
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunset
    condition: sun
  action:
  - entity_id: light.z_wave_products_inc_wd100_level_3
    service: light.turn_on
- id: '1582359841784'
  alias: porch lights on when front yard motion after dark
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door_camera_motion_detected
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.front_yard_camera_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunset
    after_offset: 01:30:00
    before: sunrise
    before_offset: 00:30:00
    condition: sun
  action:
  - entity_id: light.front_porch_lights
    service: light.turn_on
- id: '1582359845715'
  alias: porch lights on when front yard motion after dark
  description: ''
  trigger:
  - entity_id: binary_sensor.front_door_camera_motion_detected
    platform: state
    to: 'on'
  - entity_id: binary_sensor.front_yard_camera_motion
    platform: state
    to: 'on'
  condition:
  - after: sunset
    after_offset: 01:30:00
    before: sunrise
    before_offset: 00:30:00
    condition: sun
  action:
  - entity_id: light.front_porch_lights
    service: light.turn_on
- id: '1582360083628'
  alias: porch lights off if on after 10pm for more than 2 minutes
  description: ''
  trigger:
  - entity_id: light.front_porch_lights
    for: 00:02:00
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - before: sunrise
      before_offset: -00:15:00
      condition: sun
    - after: '22:00:00'
      condition: time
  action:
  - entity_id: light.front_porch_lights
    service: light.turn_off
- id: '1583941722746'
  alias: 'Internet: came back online'
  description: ''
  trigger:
  - entity_id: binary_sensor.internet_connection_status
    for: 00:03:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: The internet connection at home is back online!
    service: notify.nick
  - data:
      message: The internet is back online!
    service: script.alexa_announcement
- id: '1585787709740'
  alias: Zwift Ride On
  description: ''
  trigger:
  - event_data: {}
    event_type: ''
    platform: event
  condition: []
  action:
  - data:
      message: ride on!
    service: script.notify_alexa
  - data:
      message: ride on!
    service: notify.nick
- id: '1587237199784'
  alias: 'Nick gets Home by walking: Activate Scene'
  description: ''
  trigger:
  - entity_id: input_boolean.presence_nick_homekit
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '7'
    condition: numeric_state
    entity_id: sensor.velocity_nick
  action:
  - data: {}
    service: script.alarm_disarm
  - scene: scene.nick_gets_home_by_walking
- id: '1589162185956'
  alias: Kitchen Lights On With Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.konnected_motion_kitchen
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_sconces
    service: light.turn_on
