- id: '1534899458430'
  alias: 'Exterior Lights: On at Dusk'
  trigger:
  - event: sunset
    offset: -00:10
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.exterior_landscape_lights
    service: homeassistant.turn_on
- id: '1534899747739'
  alias: 'Exterior Lights: Off at 10pm'
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_off
- id: '1537420454578'
  alias: 'HAStatus: Shutdown'
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: brb
    service: notify.nick
- id: '1537420502502'
  alias: 'HAStatus: Start'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: back
    service: notify.nick
- id: '1537421917666'
  alias: 'Notification: Garage Door Open'
  trigger:
  - entity_id: sensor.vision_zg8101_garage_door_detector_alarm_level
    from: '0'
    platform: state
    to: '255'
  condition: []
  action:
  - data:
      message: the garage is opening
    service: notify.nick
- id: '1537936842222'
  alias: 'Alarm State: Armed, Run "Alarm State: Armed (Any)" Script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_night
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_home
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_away
  condition: []
  action:
  - service: script.alarm_state_armed_any
- id: '1537938020420'
  alias: 'Alarm State: Disarmed, run Disarmed script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: disarmed
  condition: []
  action:
  - service: script.alarm_state_disarmed
- id: '1538007620959'
  alias: 'Alarm State: Armed Night, run "Armed Night" script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_night
  condition: []
  action:
  - service: script.alarm_state_armed_night
- id: '1538111242565'
  alias: 'Security: Doop Doop when backyard motion and armed night'
  trigger:
  - entity_id: group.motion_backyard
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_night
  - condition: state
    entity_id: group.motion_front_yard
    state: 'on'
  action:
  - service: script.siren_beep_beep
- id: backyard_flood_lights_on_when_back_door_unlocked
  alias: 'Backyard Floodlights On When Back Door Unlocked '
  trigger:
  - entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: light.backyard_flood_lights
    state: 'off'
  - after: sunset
    after_offset: 00:30:00
    condition: sun
  action:
  - data:
      entity_id: light.backyard_flood_lights
    service: homeassistant.turn_on
- id: backyard_flood_lights_off_when_back_door_locked
  alias: 'Backyard Floodlights Off When Back Door Locked '
  trigger:
  - entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
    from: unlocked
    platform: state
    to: locked
  condition:
  - condition: state
    entity_id: light.backyard_flood_lights
    state: 'on'
  - after: sunset
    after_offset: 00:30:00
    condition: sun
  action:
  - data:
      entity_id: light.backyard_flood_lights
    service: homeassistant.turn_off
- id: '1547347950847'
  alias: Zwift Level Up
  trigger:
  - entity_id: sensor.zwift_level_803962
    platform: state
  condition: []
  action:
  - data:
      message: congrats on your zwift level!
    service: notify.nick
- id: '1550015887078'
  alias: disarm and unlock when nick home
  trigger:
  - entity_id: input_boolean.presence_nick_homekit
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked_2
    service: lock.unlock
  - data: {}
    service: script.alarm_disarm
- id: '1551828897602'
  alias: HA Server Overload
  trigger:
  - above: '1'
    entity_id: sensor.load_5m
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Homeassistant load has been over 1.00 for the 5m average... might want
        to look into it
    service: notify.nick
- id: '1558144520212'
  alias: turn off pool lights when you turn them on
  trigger:
  - entity_id: light.pool_light
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.pool_light
    service: light.turn_off
- id: '1561093920492'
  alias: flood lights off automatically
  trigger:
  - entity_id: light.backyard_flood_lights
    platform: state
    to: 'on'
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.backyard_flood_lights
- id: '1564508234534'
  alias: 'Pool Pump : On in the morning'
  trigger:
  - at: '8:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.pool_pump
    service: switch.turn_on
- id: '1564508283934'
  alias: 'Pool Pump: Off at night'
  trigger:
  - at: '19:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.pool_pump
    service: switch.turn_off
- id: '1567051911910'
  alias: Pantry Light Off After 5 Mins
  trigger:
  - entity_id: light.pantry_light
    for: 00:05:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.pantry_light
    service: light.turn_off
- id: '1567707738302'
  alias: Alarm trigger when doors open
  trigger:
  - entity_id: group.interior_doors
    platform: state
    to: 'On'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - data:
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_trigger
- id: '1567707885188'
  alias: Alarm triggered
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: triggered
  condition: []
  action:
  - data:
      message: alarm has been triggered!!!
    service: notify.ios_nickcell
  - data:
      message: alarm has been triggered!!
    service: notify.nick
  - data:
      entity_id: switch.linear_wa105dbz1_main_operated_siren_switch
    service: homeassistant.turn_on
- id: '1567707958845'
  alias: Alarm triggered stop
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    from: triggered
    platform: state
  condition: []
  action:
  - data:
      entity_id: switch.linear_wa105dbz1_main_operated_siren_switch
    service: homeassistant.turn_off
- id: '1573699277520'
  alias: Garage Lights Off After 5 Mins No Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.garage_camera_motion
    for: 00:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.garage_overhead_light
    service: light.turn_off
- id: '1573699508759'
  alias: Garage Lights On If Doors Open After Dusk
  description: ''
  trigger:
  - above: '0'
    entity_id: sensor.garage_door_position
    for: 00:00:01
    platform: numeric_state
  - entity_id: binary_sensor.garage_interior_door
    from: closed
    platform: state
    to: open
  condition:
  - after: sunset
    after_offset: -00:30:00
    before: sunrise
    condition: sun
  action:
  - data:
      entity_id: light.garage_overhead_light
    service: homeassistant.turn_off
