- id: '1534899458430'
  alias: 'Exterior Lights: On at Dusk'
  trigger:
  - event: sunset
    offset: -00:10
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.exterior_landscape_lights
    service: homeassistant.turn_on
- id: '1534899747739'
  alias: 'Exterior Lights: Off at 10pm'
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.exterior_lights
    service: homeassistant.turn_off
- id: '1537420454578'
  alias: 'HAStatus: Shutdown'
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: brb
    service: notify.nick
- id: '1537420502502'
  alias: 'HAStatus: Start'
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: back
    service: notify.nick
- id: '1537421917666'
  alias: 'Notification: Garage Door Open'
  trigger:
  - entity_id: sensor.vision_zg8101_garage_door_detector_alarm_level
    from: '0'
    platform: state
    to: '255'
  condition: []
  action:
  - data:
      message: the garage is opening
    service: notify.nick
- id: '1537936842222'
  alias: 'Alarm State: Armed, Run "Alarm State: Armed (Any)" Script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_night
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_home
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_away
  condition: []
  action:
  - service: script.alarm_state_armed_any
- id: '1537938020420'
  alias: 'Alarm State: Disarmed, run Disarmed script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: disarmed
  condition: []
  action:
  - service: script.alarm_state_disarmed
- id: '1538007620959'
  alias: 'Alarm State: Armed Night, run "Armed Night" script'
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: armed_night
  condition: []
  action:
  - service: script.alarm_state_armed_night
- id: '1538111242565'
  alias: 'Security: Doop Doop when backyard motion and armed night'
  trigger:
  - entity_id: group.motion_backyard
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_night
  - condition: state
    entity_id: group.motion_front_yard
    state: 'on'
  action:
  - service: script.siren_beep_beep
- id: backyard_flood_lights_on_when_back_door_unlocked
  alias: 'Backyard Floodlights On When Back Door Unlocked '
  trigger:
  - entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: light.backyard_flood_lights
    state: 'off'
  - after: sunset
    after_offset: 00:30:00
    condition: sun
  action:
  - data:
      entity_id: light.backyard_flood_lights
    service: homeassistant.turn_on
- id: backyard_flood_lights_off_when_back_door_locked
  alias: 'Backyard Floodlights Off When Back Door Locked '
  trigger:
  - entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
    from: unlocked
    platform: state
    to: locked
  condition:
  - condition: state
    entity_id: light.backyard_flood_lights
    state: 'on'
  - after: sunset
    after_offset: 00:30:00
    condition: sun
  action:
  - data:
      entity_id: light.backyard_flood_lights
    service: homeassistant.turn_off
- id: '1547347950847'
  alias: Zwift Level Up
  trigger:
  - entity_id: sensor.zwift_level_803962
    platform: state
  condition: []
  action:
  - data:
      message: congrats on your zwift level!
    service: notify.nick
- id: '1550015887078'
  alias: disarm and unlock when nick home
  trigger:
  - entity_id: input_boolean.presence_nick_homekit
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: lock.unlock
  - data: {}
    service: script.alarm_disarm
