###################################################################################################
## Package - Unavailable Entities Sensor
## Count and list entities with a state of unavailable, unknown, or none (null)
## See README for customization options.
## https://github.com/jazzyisj/unavailable-entities-sensor/blob/main/README.md
###################################################################################################
## Modified by snicker to support monitoring connectivity sensors for anything that is disconnected
###################################################################################################

input_boolean:
  offline_devices_automation_test_switch:
    name: "Offline Devices Automation Test Device Online Switch"

template:
  - binary_sensor:
    - name: "Offline Devices Automation Test Device Online"
      unique_id: offline_devices_automation_test_device_online
      device_class: connectivity
      state: >
        {{ is_state('input_boolean.offline_devices_automation_test_switch','on') }}

  - sensor:
      - name: "Offline Devices"
        unique_id: offline_devices
        icon: "{{ iif(states(this.entity_id)|int(-1) > 0,'mdi:alert-circle','mdi:check-circle') }}"
        unit_of_measurement: entities
        state: >
          {% set entities = state_attr(this.entity_id,'entity_id') %}
          {{ entities|count if entities != none else none }}
        attributes:
          entity_id: >
            {% set ignore_seconds = 90 %}
            {% set ignored = state_attr('group.ignored_connectivity_sensors','entity_id') %}
            {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
            {% set entities = states.binary_sensor|rejectattr('attributes.device_class', 'undefined')|selectattr('state','in',['unknown','unavailable','off'])|selectattr('attributes.device_class','in',['connectivity'])|list %}
            {% set entities =  entities|rejectattr('entity_id','in',ignored)
                if ignored != none else entities %}
            {{ entities|map(attribute='entity_id')|list }}
          help: "To supress alerts, add the 'exclude_from_connectivity_alerts' attribute to the entity as true or add to the ignored_connectivity_sensors group."

group:
  ignored_connectivity_sensors:
    entities:
      - sensor.offline_devices # prevent template loop warnings?

# OPTIONAL - filter template loop warnings from the Home Assistant log.
logger:
  filters:
    homeassistant.components.template.template_entity:
      - 'Template loop detected while processing event'

# OPTIONAL Example automation to demonstrate how you can utilize this sensor
automation:
  - id: offline_devices_notification
    alias: 'Offline Devices Notification'
    description: 'Create persistent notification if there are offline devices, dismiss if none.'
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.offline_devices
        attribute: entity_id
    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state.attributes.entity_id | length > -1 and 
              trigger.to_state.attributes.entity_id | length > -1 }}
    action:
      - choose: # device has come back online
          conditions: >
            {{ trigger.from_state.attributes.entity_id | length > trigger.to_state.attributes.entity_id | length }}
          sequence:
            - service: notify.mobile_app_spacecell
              data_template:
                title: "Device Back Online"
                message: >
                  {% set online = trigger.from_state.attributes.entity_id | reject('in',trigger.to_state.attributes.entity_id) | list  %}
                  {{ expand(online)
                    |map(attribute='attributes.friendly_name')
                    |map('replace',' Online','')
                    |map('replace',' Status','')
                    |map('replace',' online sensor','')
                    |join(', ')}} is online!
                data:
                  group: "offline-device-notifications"
      - choose: # device has gone offline
          conditions: >
            {{ trigger.to_state.attributes.entity_id | length > trigger.from_state.attributes.entity_id | length }}
          sequence:
            - service: notify.mobile_app_spacecell
              data_template:
                title: "Device Offline!"
                message: >
                  {% set offline = trigger.to_state.attributes.entity_id | reject('in',trigger.from_state.attributes.entity_id) | list  %}
                  {{ expand(offline)
                    |map(attribute='attributes.friendly_name')
                    |map('replace',' Online','')
                    |map('replace',' Status','')
                    |map('replace',' online sensor','')
                    |join(', ')}} is offline!
                data:
                  group: "offline-device-notifications"
      - choose:
          conditions:
            - condition: numeric_state
              entity_id: sensor.offline_devices
              below: 1
          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: offline_devices
        default:
          - service: persistent_notification.create
            data:
              title: 'Offline Devices'
              message: >
                The following devices are offline!

                - {{ expand(state_attr('sensor.offline_devices','entity_id'))
                    |map(attribute='attributes.friendly_name')
                    |map('replace',' Online','')
                    |map('replace',' Status','')
                    |map('replace',' online sensor','')
                    |join('\n- ') }}
              notification_id: offline_devices