homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'edmond_came_inside'
        
    automation.edmond_came_inside_alert:
      <<: *customize
        
    automation.disable_edmond_came_inside_alert:
      <<: *customize
        
    switch.edmond_is_outside:
      <<: *customize
      
switch:
  - platform: template
    switches:
      edmond_is_outside:
        value_template: "{{ is_state('automation.edmond_came_inside_alert', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: automation.edmond_came_inside_alert
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: automation.edmond_came_inside_alert

automation:

  - alias: 'edmond_came_inside_alert'
    trigger:
    - entity_id: 
      - binary_sensor.back_door
      from: 'off'
      platform: state
      to: 'on'
    - platform: time_pattern
      minutes: '/1'
      seconds: 00
    condition: []
    action:
    - condition: template
      value_template: "{{ is_state('binary_sensor.back_door', 'on') }}"
    - service: script.notify_200stonewood
      data_template:
        message: &door_open_message >
          Edmond came inside! Close the back door!
    - service: script.alexa_announcement
      data_template:
        message: *door_open_message
        
  - alias: 'disable_edmond_came_inside_alert'
    trigger:
    - entity_id:
      - binary_sensor.back_door
      from: 'on'
      platform: state
      to: 'off'
    condition: []
    action:
    - service: homeassistant.turn_off
      data:
        entity_id: automation.edmond_came_inside_alert