
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'ballet_studio_camera'
    
    camera.yi_home_camera_ballet_studio:
      <<: *customize
      friendly_name: "Ballet Studio Camera"
      icon: mdi:cctv
    
    binary_sensor.ballet_studio_camera_motion_sensor:
      <<: *customize
    
    binary_sensor.ballet_studio_camera_motion_sensor_debounced:
      <<: *customize
      friendly_name: "Motion - Ballet Studio (Camera)"
      camera_entity_id: "yi_home_camera_ballet_studio"
      
    binary_sensor.ballet_studio_camera_status:
      <<: *customize
      friendly_name: "Ballet Studio Camera Status"
      device_class: connectivity

camera:
  - platform: generic
    name: yi_home_camera_ballet_studio
    still_image_url: https://192.168.1.237/cgi-bin/currentpic.cgi
    stream_source: rtsp://192.168.1.237:8554/unicast
    verify_ssl: false
    authentication: basic
    username: root
    password: !secret dafang_cam_password
    
binary_sensor:
  - platform: ping
    name: ballet_studio_camera_status
    host: 192.168.1.237
    count: 3
    scan_interval: 60
  - platform: template
    sensors:
      ballet_studio_camera_motion_sensor_debounced:
        value_template: "{{ is_state('binary_sensor.ballet_studio_camera_motion_sensor','on') }}"
        device_class: motion
        delay_off: "00:00:10"
    
group:
  ballet_studio_camera:
    name: "Ballet Studio Camera Settings"
    
    entities:
    - camera.yi_home_camera_ballet_studio
    - switch.ballet_studio_camera_h264_rtsp_server
    - switch.ballet_studio_camera_mjpeg_rtsp_server
    - sensor.ballet_studio_camera_status
    - sensor.ballet_studio_camera_light_sensor
    - switch.ballet_studio_camera_ir_filter
    - switch.ballet_studio_camera_ir_led
    - switch.ballet_studio_camera_night_mode
    - switch.ballet_studio_camera_night_mode_auto
    - switch.ballet_studio_camera_blue_led
    - switch.ballet_studio_camera_yellow_led
    - switch.ballet_studio_camera_motion_detection
    - switch.ballet_studio_camera_motion_tracking
    - camera.ballet_studio_camera_motion_snapshot
    - binary_sensor.ballet_studio_camera_motion_sensor