
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'front_driveway_camera'
    
    camera.front_driveway_camera:
      <<: *customize
      friendly_name: "Front Driveway Camera"
      ip_address: 192.168.1.209
      icon: mdi:cctv
    
    binary_sensor.front_driveway_camera_motion_sensor:
      <<: *customize
    
    binary_sensor.front_driveway_camera_motion_sensor_debounced:
      <<: *customize
      friendly_name: "Motion - Front Driveway (Camera)"
      camera_entity_id: "front_driveway_camera"
      
    binary_sensor.front_driveway_camera_status:
      <<: *customize
      friendly_name: "Front Driveway Camera Status"
      device_class: connectivity

camera:
  - platform: generic
    name: front_driveway_camera
    still_image_url: https://192.168.1.209/cgi-bin/currentpic.cgi
    stream_source: rtsp://192.168.1.209:8554/unicast
    verify_ssl: false
    authentication: basic
    username: root
    password: !secret dafang_cam_password

rest_command:
  camera_reboot_front_driveway:
    url: 'https://192.168.1.209/cgi-bin/action.cgi?cmd=reboot'
    verify_ssl: false
    username: root
    password: !secret dafang_cam_password

automation:
  - alias: camera_reboot_front_driveway_nightly
    trigger:
      platform: time
      at: "01:00:00"
    action:
      - delay: '00:0{{ range(1,2) | random | int }}:{{ range(10,60) | random | int }}'
      - service: rest_command.camera_reboot_front_driveway

template:
  - binary_sensor:
    - name: front_driveway_camera_status
      device_class: connectivity
      state: |-
        {% set to_monitor = 'front_driveway_camera_uptime' %}
        {% set delay = 120 %}
        {{ as_timestamp(now()) - as_timestamp(states.sensor[to_monitor].last_changed) <= delay }}
    - name: "front_driveway_camera_motion_sensor_debounced"
      state: "{{ is_state('binary_sensor.front_driveway_camera_motion_sensor','on') }}"
      device_class: motion
      delay_off: "00:00:10"

mqtt:
  sensor:
    - name: "Front Driveway Camera Uptime"
      unique_id: front_driveway_camera_uptime
      object_id: front_driveway_camera_uptime
      device:
        identifiers:
          - front_driveway_camera
          - 2caa8e96a925
      entity_category: diagnostic
      value_template: "{{ value_json.uptime }}"
      state_topic: driveway/front_driveway_camera
      json_attributes_topic: driveway/front_driveway_camera
