homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'front_yard_camera'
    
    camera.front_yard_camera:
      <<: *customize
      friendly_name: "Front Yard Camera"
      ip_address: 192.168.1.75
      icon: mdi:cctv
    
    binary_sensor.front_yard_camera_motion:
      <<: *customize
      friendly_name: "Motion - Front Yard (Camera)"
      camera_entity_id: "front_yard_camera"
      
    binary_sensor.front_yard_camera_status:
      <<: *customize
      friendly_name: "Front Yard Camera Status"
      device_class: connectivity

camera:
  - platform: generic
    name: front_yard_camera
    still_image_url: http://192.168.1.75:8080/cgi-bin/snapshot.sh?res=low
    stream_source: rtsp://192.168.1.75:554/ch0_0.h264

mqtt:
  binary_sensor:
    - name: front_yard_camera_motion
      state_topic: "cameras/yicam3/motion"
      payload_on: "motion_start"
      payload_off: "motion_stop"
      device_class: motion
    
template:
  - binary_sensor:
    - name: front_yard_camera_status
      device_class: connectivity
      state: |-
        {% set to_monitor = 'front_yard_camera' %}
        {{ states('device_tracker.' + to_monitor) == 'home' }}