homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'garage_camera'
        
    camera.yi_home_camera_garage:
      <<: *customize
      friendly_name: "Garage Camera"
      ip_address: 192.168.1.72
      icon: mdi:cctv
    
    binary_sensor.garage_camera_motion:
      <<: *customize
      friendly_name: "Motion - Garage (Camera)"
      camera_entity_id: "yi_home_camera_garage"
      
    binary_sensor.garage_camera_status:
      <<: *customize
      friendly_name: "Garage Camera Status"
      device_class: connectivity


camera:
  - platform: ffmpeg
    name: yi_home_camera_garage
    input: -rtsp_transport tcp -i rtsp://192.168.1.72:554/ch0_1.h264
    
binary_sensor:
  - platform: template
    sensors:
      garage_camera_motion:
        device_class: motion
        value_template: "{{ states('sensor.yi_camera_motion_garage')|int == 1 }}"

template:
  - binary_sensor:
    - name: garage_camera_status
      device_class: connectivity
      state: |-
        {% set to_monitor = 'garage_camera' %}
        {{ states('device_tracker.' + to_monitor) == 'home' }}