
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'living_room_camera'
    
    camera.living_room_camera:
      <<: *customize
      friendly_name: "Living Room Camera"
      icon: mdi:cctv
    
    binary_sensor.living_room_camera_motion_sensor:
      <<: *customize
    
    binary_sensor.living_room_camera_motion_sensor_debounced:
      <<: *customize
      friendly_name: "Motion - Living Room (Camera)"
      camera_entity_id: "living_room_camera"
      
    binary_sensor.living_room_camera_status:
      <<: *customize
      friendly_name: "Living Room Camera Status"
      device_class: connectivity

camera:
  - platform: generic
    name: yi_home_camera_ballet_studio
    still_image_url: https://192.168.1.238/cgi-bin/currentpic.cgi
    stream_source: rtsp://192.168.1.238:8554/unicast
    verify_ssl: false
    authentication: basic
    username: root
    password: !secret dafang_cam_password
    
binary_sensor:
  - platform: ping
    name: living_room_camera_status
    host: 192.168.1.238
    count: 3
    scan_interval: 60
  - platform: template
    sensors:
      living_room_camera_motion_sensor_debounced:
        value_template: "{{ is_state('binary_sensor.living_room_camera_motion_sensor','on') }}"
        device_class: motion
        delay_off: "00:00:10"
    
group:
  living_room_camera:
    name: "Living Room Camera Settings"
    control: hidden
    view: no
    entities:
    - camera.living_room_camera
    - switch.living_room_camera_h264_rtsp_server
    - switch.living_room_camera_mjpeg_rtsp_server
    - sensor.living_room_camera_status
    - sensor.living_room_camera_light_sensor
    - switch.living_room_camera_ir_filter
    - switch.living_room_camera_ir_led
    - switch.living_room_camera_night_mode
    - switch.living_room_camera_night_mode_auto
    - switch.living_room_camera_blue_led
    - switch.living_room_camera_yellow_led
    - switch.living_room_camera_motion_detection
    - switch.living_room_camera_motion_tracking
    - camera.living_room_camera_motion_snapshot
    - binary_sensor.living_room_camera_motion_sensor