
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'living_room_camera'
    
    camera.living_room_camera:
      <<: *customize
      friendly_name: "Living Room Camera"
      ip_address: 192.168.1.238
      icon: mdi:cctv
    
    binary_sensor.living_room_camera_motion_sensor:
      <<: *customize
    
    binary_sensor.living_room_camera_motion_sensor_debounced:
      <<: *customize
      friendly_name: "Motion - Living Room (Camera)"
      camera_entity_id: "living_room_camera"
      
    binary_sensor.living_room_camera_status:
      <<: *customize
      friendly_name: "Living Room Camera Status"
      device_class: connectivity

rest_command:
  camera_reboot_living_room:
    url: 'https://192.168.1.238/cgi-bin/action.cgi?cmd=reboot'
    verify_ssl: false
    username: root
    password: !secret dafang_cam_password

automation:
  - alias: camera_reboot_living_room_nightly
    trigger:
      platform: time
      at: "01:00:00"
    action:
      - delay: '00:0{{ range(1,2) | random | int }}:{{ range(10,60) | random | int }}'
      - service: rest_command.camera_reboot_living_room

template:
  - binary_sensor:
    - name: living_room_camera_status
      device_class: connectivity
      state: |-
        {% set to_monitor = 'living_room_camera_uptime' %}
        {% set delay = 120 %}
        {% set recent_update = as_timestamp(now()) - as_timestamp(states.sensor[to_monitor].last_changed) <= delay %}
        {% set to_monitor = 'wyze_livingroom' %}
        {% set unifi_online = states('device_tracker.' + to_monitor) == 'home' %}
        {{ recent_update or unifi_online }}
    - name: "living_room_camera_motion_sensor_debounced"
      state: "{{ is_state('binary_sensor.living_room_camera_motion_sensor','on') }}"
      device_class: motion
      delay_off: "00:00:10"

mqtt:
  sensor:
    - name: "Living Room Camera Uptime"
      unique_id: living_room_camera_uptime
      object_id: living_room_camera_uptime
      device:
        identifiers:
          - living_room_camera
          - 2caa8e170010
      entity_category: diagnostic
      value_template: "{{ value_json.uptime }}"
      state_topic: twohunnid/living_room_camera
      json_attributes_topic: twohunnid/living_room_camera
    
group:
  living_room_camera:
    name: "Living Room Camera Settings"
    
    entities:
    - camera.living_room_camera
    - switch.living_room_camera_h264_rtsp_server
    - switch.living_room_camera_mjpeg_rtsp_server
    - sensor.living_room_camera_status
    - sensor.living_room_camera_light_sensor
    - switch.living_room_camera_ir_filter
    - switch.living_room_camera_ir_led
    - switch.living_room_camera_night_mode
    - switch.living_room_camera_night_mode_auto
    - switch.living_room_camera_blue_led
    - switch.living_room_camera_yellow_led
    - switch.living_room_camera_motion_detection
    - switch.living_room_camera_motion_tracking
    - camera.living_room_camera_motion_snapshot
    - binary_sensor.living_room_camera_motion_sensor