
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'south_driveway_camera'
    
    camera.south_driveway_camera:
      <<: *customize
      friendly_name: "South Driveway Camera"
      ip_address: 192.168.1.186
      icon: mdi:cctv
    
    binary_sensor.south_driveway_camera_motion_sensor:
      <<: *customize
    
    binary_sensor.south_driveway_camera_motion_sensor_debounced:
      <<: *customize
      friendly_name: "Motion - South Driveway (Camera)"
      camera_entity_id: "south_driveway_camera"
      
    binary_sensor.south_driveway_camera_status:
      <<: *customize
      friendly_name: "South Driveway Camera Status"
      device_class: connectivity

rest_command:
  camera_reboot_south_driveway:
    url: 'https://192.168.1.186/cgi-bin/action.cgi?cmd=reboot'
    verify_ssl: false
    username: root
    password: !secret dafang_cam_password

automation:
  - alias: camera_reboot_south_driveway_nightly
    trigger:
      platform: time
      at: "01:00:00"
    action:
      - delay: '00:0{{ range(1,2) | random | int }}:{{ range(10,60) | random | int }}'
      - service: rest_command.camera_reboot_south_driveway

template:
  - binary_sensor:
    - name: south_driveway_camera_status
      device_class: connectivity
      state: |-
        {% set to_monitor = 'south_driveway_camera_uptime' %}
        {% set delay = 180 %}
        {% set recent_update = as_timestamp(now()) - as_timestamp(states.sensor[to_monitor].last_changed) <= delay %}
        {% set to_monitor = 'south_driveway_camera' %}
        {% set unifi_online = states('device_tracker.' + to_monitor) == 'home' %}
        {{ recent_update or unifi_online }}
    - name: "south_driveway_camera_motion_sensor_debounced"
      state: "{{ is_state('binary_sensor.south_driveway_camera_motion_sensor','on') }}"
      device_class: motion
      delay_off: "00:00:10"

mqtt:
  sensor:
    - name: "South Driveway Camera Uptime"
      unique_id: south_driveway_camera_uptime
      object_id: south_driveway_camera_uptime
      device:
        identifiers:
          - south_driveway_camera
          - 2caa8e974ae4
      entity_category: diagnostic
      value_template: "{{ value_json.uptime }}"
      state_topic: south_driveway/south_driveway_camera
      json_attributes_topic: south_driveway/south_driveway_camera