ios:
  push:
    categories:
      - name: Camera
        identifier: 'camera'
        actions:
          - identifier: 'IOS_CAMERA_YES'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: true
            destructive: no
          - identifier: 'IOS_CAMERA_NO'
            title: 'No'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            
      - name: Garage Door
        identifier: 'garage_door'
        actions:
          - identifier: 'CLOSE_GARAGE'
            title: 'Close the Garage'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'
          - identifier: 'OPEN_GARAGE'
            title: 'Open the Garage'
            activationMode: 'background'
            authenticationRequired: true
            destructive: false
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'ARM_AWAY'
            title: 'Arm Away'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'
          - identifier: 'ARM_DISARM'
            title: 'Disarm'
            activationMode: 'background'
            authenticationRequired: true
            destructive: false

automation:
  - alias: ios_camera_yes_pressed
    id: ios_camera_yes_pressed
    trigger: 
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: IOS_CAMERA_YES
    action:
      - service: notify.nick
        data_template:
          message: "{{ trigger.event.data }}"
      - condition: template
        value_template: "{{ states(trigger.event.data['actiondata']['yes_script']) != 'unknown' }}"
      - service: script.turn_on
        data_template:
          entity_id: "{{ trigger.event.data['actiondata']['yes_script'] }}"
  - alias: ios_camera_no_pressed
    id: ios_camera_no_pressed
    trigger: 
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: IOS_CAMERA_NO
    action:
      - service: notify.nick
        data_template:
          message: "{{ trigger.event.data }}"
      - condition: template
        value_template: "{{ states(trigger.event.data['actiondata']['no_script']) != 'unknown' }}"
      - service: script.turn_on
        data_template:
          entity_id: "{{ trigger.event.data['actiondata']['no_script'] }}"