homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'motion_indoor_foyer'
    
    binary_sensor.motion_indoor_foyer:
      <<: *customize
      friendly_name: "Motion - Indoor Foyer"
      device_class: motion
      
    sensor.vision_zp3111_multisensor_4in1_battery_level:
      <<: *customize
      friendly_name: "Motion - Indoor Foyer - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
     
binary_sensor:
  - platform: template
    sensors:
      motion_indoor_foyer:
        entity_id: sensor.vision_zp3111_multisensor_4in1_alarm_level
        value_template: "{{ states('sensor.vision_zp3111_multisensor_4in1_alarm_level')|int == 255 }}"