homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'motion_backyard_south'
    
    binary_sensor.motion_backyard_south:
      <<: *customize
      friendly_name: "Motion - Backyard (South)"
      device_class: motion
      
    sensor.vision_zp3102_pir_motion_sensor_battery_level_2:
      <<: *customize
      friendly_name: "Motion - Backyard (South) - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
     
binary_sensor:
  - platform: template
    sensors:
      motion_backyard_south:
        entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level_2
        value_template: "{{ states('sensor.vision_zp3102_pir_motion_sensor_alarm_level_2')|int == 255 }}"