homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'motion_front_driveway'
    
    binary_sensor.motion_front_driveway:
      <<: *customize
      friendly_name: "Motion - Front Driveway"
      device_class: motion
      
    sensor.vision_zp3102_pir_motion_sensor_battery_level_4:
      <<: *customize
      friendly_name: "Motion - Front Driveway (Battery)"
      device_class: battery
      unit_of_measurement: '%'
      
     
binary_sensor:
  - platform: template
    sensors:
      motion_front_driveway:
        entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level_4
        value_template: "{{ states('sensor.vision_zp3102_pir_motion_sensor_alarm_level_4')|int == 255 }}"