################################################################
## Packages / fiddle_leaf_fig
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_fiddle_leaf_fig'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.fiddle_leaf_fig:
      <<: *customize
      friendly_name: Crown of Thorns
      battery_sensor_creation_disabled: true
      
    sensor.plant_fiddle_leaf_fig_battery:
      <<: *customize
      friendly_name: "Crown of Thorns - Battery"
      
    sensor.plant_fiddle_leaf_fig_moisture:
      <<: *customize
      friendly_name: "Crown of Thorns - Moisture"
      
    sensor.plant_fiddle_leaf_fig_temperature:
      <<: *customize
      friendly_name: "Crown of Thorns - Temperature"
        
    sensor.plant_fiddle_leaf_fig_light:
      <<: *customize
      friendly_name: "Crown of Thorns - Brightness"
      
    sensor.plant_fiddle_leaf_fig_conductivity:
      <<: *customize
      friendly_name: "Crown of Thorns - Conductivity"
    
        
        
plant:
  fiddle_leaf_fig:
    sensors:
      moisture: sensor.plant_fiddle_leaf_fig_moisture
      battery: sensor.plant_fiddle_leaf_fig_battery
      temperature: sensor.plant_fiddle_leaf_fig_temperature
      conductivity: sensor.plant_fiddle_leaf_fig_conductivity
      brightness: sensor.plant_fiddle_leaf_fig_light
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90

automation:
  - id: fiddle_leaf_fig_notify_problems
    alias: 'Crown of Thorns Notify of Problems'
    trigger:
    - platform: time_pattern
      minutes: '/59'
      seconds: 00
    - entity_id: plant.fiddle_leaf_fig
      platform: state
      to: problem
    condition: []
    action:
    - condition: template
      value_template: "{{ state_attr('plant.fiddle_leaf_fig','problem') != 'none' }}"
    - data_template:
        message: "{% set plant = 'plant.fiddle_leaf_fig' %}{{ state_attr(plant,'friendly_name') }} has an issue: {{ state_attr(plant,'problem') }}. Moisture: {{ state_attr(plant,'moisture') }}% Temp: {{ state_attr(plant,'temperature') }} Conductivity: {{ state_attr(plant,'conductivity') }}"
      service: notify.nick