################################################################
## Packages / zebra_plant
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_zebra_plant'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.zebra_plant:
      <<: *customize
      friendly_name: Fiddle Leaf Fig
      battery_sensor_creation_disabled: true
      
    sensor.plant_zebra_plant_battery:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Battery"
      
    sensor.plant_zebra_plant_moisture:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Moisture"
      
    sensor.plant_zebra_plant_temperature:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Temperature"
        
    sensor.plant_zebra_plant_light:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Brightness"
      
    sensor.plant_zebra_plant_conductivity:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Conductivity"
    
        
        
plant:
  zebra_plant:
    sensors:
      moisture: sensor.plant_zebra_plant_moisture
      battery: sensor.plant_zebra_plant_battery
      temperature: sensor.plant_zebra_plant_temperature
      conductivity: sensor.plant_zebra_plant_conductivity
      brightness: sensor.plant_zebra_plant_light
    min_moisture: 20
    max_moisture: 80
    min_battery: 15
    min_conductivity: 200
    min_temperature: 40
    max_temperature: 90
        
automation:
  - id: zebra_plant_notify_problems
    alias: 'Fiddle Leaf Fig Notify of Problems'
    trigger:
    - platform: time_pattern
      minutes: '/59'
      seconds: 00
    - entity_id: plant.zebra_plant
      platform: state
      to: problem
    condition: []
    action:
    - condition: template
      value_template: "{{ state_attr('plant.zebra_plant','problem') != 'none' }}"
    - data_template:
        message: "{% set plant = 'plant.zebra_plant' %}{{ state_attr(plant,'friendly_name') }} has an issue: {{ state_attr(plant,'problem') }}. Moisture: {{ state_attr(plant,'moisture') }}% Temp: {{ state_attr(plant,'temperature') }} Conductivity: {{ state_attr(plant,'conductivity') }}"
      service: script.notify_200stonewood