################################################################
## Packages / zebra_plant
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_zebra_plant'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.zebra_plant:
      <<: *customize
      friendly_name: Zebra Plant
      battery_sensor_creation_disabled: true
      
    sensor.plant_zebra_plant_battery:
      <<: *customize
      friendly_name: "Zebra Plant - Battery"
      
    sensor.plant_zebra_plant_moisture:
      <<: *customize
      friendly_name: "Zebra Plant - Moisture"
      
    sensor.plant_zebra_plant_temperature:
      <<: *customize
      friendly_name: "Zebra Plant - Temperature"
        
    sensor.plant_zebra_plant_light:
      <<: *customize
      friendly_name: "Zebra Plant - Brightness"
      
    sensor.plant_zebra_plant_conductivity:
      <<: *customize
      friendly_name: "Zebra Plant - Conductivity"
    
        
        
plant:
  zebra_plant:
    sensors:
      moisture: sensor.plant_zebra_plant_moisture
      battery: sensor.plant_zebra_plant_battery
      temperature: sensor.plant_zebra_plant_temperature
      conductivity: sensor.plant_zebra_plant_conductivity
      brightness: sensor.plant_zebra_plant_light
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90
        
automation:
  - id: zebra_plant_notify_problems
    alias: 'Zebra Plant Notify of Problems'
    trigger:
    - entity_id: plant.zebra_plant
      platform: state
      to: problem
    condition: []
    action:
    - data_template:
        message: "Zebra Plant has an issue: {{ trigger.to_state.attributes.problem }}. Moisture: {{ trigger.to_state.attributes.moisture }}% Temp: {{ trigger.to_state.attributes.temperature }} Conductivity: {{ trigger.to_state.attributes.conductivity }}"
      service: notify.nick