homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'universal_media_player_living_room'
    media_player.universal_media_player_living_room:
      <<: *customize
      friendly_name: "Television - Living Room"
      icon: mdi:television
      
media_player:
  - platform: universal
    name: universal_media_player_living_room
    state_template: >
      {% if is_state('media_player.living_room_television', 'off') %}
        off
      {% elif not is_state('media_player.aftmm','unavailable') %}
        {{ states('media_player.aftmm') }}
      {% elif is_state_attr('media_player.spotify','source','Living Room Fire TV') %}
        {{ states('media_player.spotify') }}
      {% endif %}
    children:
      - media_player.living_room_fire_tv
      - media_player.aftmm
      - media_player.living_room_television
      - media_player.spotify
    commands:
      turn_on:
        service: media_player.turn_on
        data: 
          entity_id: media_player.living_room_television
      turn_off:
        service: media_player.turn_off
        data: 
          entity_id: media_player.living_room_television
      volume_up:
        service: media_player.volume_up
        data: 
          entity_id: media_player.living_room_television
      volume_down:
        service: media_player.volume_down
        data: 
          entity_id: media_player.living_room_television
      volume_mute:
        service: media_player.volume_mute
        data: 
          entity_id: media_player.living_room_television
    attributes:
      is_volume_muted: media_player.living_room_television|is_volume_muted