homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'google_maps_nick'
      
    device_tracker.google_maps_nick:
      <<: *customize
      friendly_name: "Nick (GMaps)"
        
device_tracker:
  - platform: google_maps
    username: !secret device_tracker_gmail_username
    password: !secret device_tracker_gmail_password
    max_gps_accuracy: 250