homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'life360'
        
    device_tracker.life360_nick:
      <<: *customize
      friendly_name: "Nick (Life360)"
      battery_alert_disabled: true
        
device_tracker:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 25
    max_gps_accuracy: 200
    time_as: device_or_local
    max_update_wait:
      minutes: 45