cloud:
  alexa:
    filter:
      include_domains:
        - light
      include_entities:
        - switch.backyard_amplifier
        - script.alarm_arm_away
        - script.alarm_arm_night
        - group.exterior_lights
        - group.interior_lights
        - group.all_lights
        - group.interior_christmas_lights
        - media_player.universal_media_player_living_room
        - switch.pool_pump
        - switch.coffee_grinder
        - switch.master_bedroom_humidifier
        - cover.garage_door
        - sensor.garage_door_status
        - switch.edmond_is_outside
        - switch.xiaomi_vacuum
        - binary_sensor.front_door_camera_person_detected
        - alarm_control_panel.home_alarm
        - lock.kwikset_touchpad_electronic_deadbolt_locked
        - lock.kwikset_touchpad_electronic_deadbolt_locked_2
        - script.tesla_climate_activate
      exclude_entities:
        - switch.garage_door_relay
        - light.pantry_light
        - light.front_landscape_lights_power
        - light.north_pine_landscape_light
        - light.front_pine_landscape_light
        - light.ash_landscape_light
        - light.olive_landscape_light
        - light.all_front_landscape_lights
        - light.jasco_products_26933_smart_motion_dimmer_level_2
        - light.jasco_products_26933_smart_motion_dimmer_level
        - light.front_porch_lights_power
        - light.front_porch_bottom_left
        - light.front_porch_bottom_right
        - light.front_porch_upper_left
        - light.front_porch_upper_right
        - light.front_porch_left
        - light.front_porch_right
        - light.front_porch_all_lights
        - light.remotec_unknown_type_8200_id_8130_level
        - light.remotec_unknown_type_8200_id_8130_level_2
    entity_config:
      script.alarm_arm_away:
        name: Home Security
        description: Arm Home Security for Away Mode
      script.alarm_arm_night:
        name: Night Security
        description: Arm Home Security for Night Mode
      media_player.universal_media_player_living_room:
        name: TV
        description: Living room television
      binary_sensor.front_door_camera_person_detected:
        display_categories: DOORBELL
        name: Front Door
        description: Front Door Bell sensor
        

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      
notify:
  - platform: alexa_media
    name: alexa_media
    
group:
  alexa_all_media_players:
    name: "All Alexas"
    control: hidden
    view: no
    entities:
    - media_player.backyard_dot
    - media_player.kitchen_dot
    - media_player.master_bedroom_dot
    - media_player.plant_room_dot
    - media_player.master_bed_fire_tv
    - media_player.living_room_fire_tv
    - media_player.ballet_studio_fire_tv
    - media_player.nicholas_s_2nd_echo_input
  alexa_notification_media_players:
    - media_player.backyard_dot
    - media_player.kitchen_dot
    - media_player.master_bedroom_dot
    - media_player.ballet_studio_fire_tv
    - media_player.nicholas_s_2nd_echo_input
    
script:
  alexa_announcement_all:
    alias: "Send announcement to all Alexas"
    sequence:
    - service: script.notify_alexa
      data_template: 
        message: "{{ message }}"
        title: "{{ title }}"
        alexa: group.alexa_all_media_players
  alexa_announcement:
    alias: "Send announcement to main Alexas"
    sequence:
    - service: script.notify_alexa
      data_template: 
        message: "{{ message }}"
        title: "{{ title }}"
        alexa: group.alexa_notification_media_players
  notify_alexa:
    alias: "Notify one Alexa"
    sequence:
    - service: notify.alexa_media
      data_template: 
        message: "{{ message }}"
        title: "{{ title or 'Notice'}}"
        target: "{{ alexa }}"
        data:
          type: announce
          method: all
    
sensor:
  - platform: template
    sensors:
      last_alexa:
        entity_id:
          - media_player.backyard_dot
          - media_player.kitchen_dot
          - media_player.master_bedroom_dot
          - media_player.plant_room_dot
          - media_player.master_bed_fire_tv
          - media_player.living_room_fire_tv
          - media_player.ballet_studio_fire_tv
          - media_player.nicholas_s_2nd_echo_input
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}