homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'coffee_grinder'
        
    switch.25048234840d8ebe0e6e:
      <<: *customize
      hidden: true
    
    switch.coffee_grinder:
      <<: *customize
      friendly_name: "Coffee Grinder"

switch:
  - platform: template
    switches:
      backyard_amplifier:
        value_template: "{{ is_state('switch.25048234840d8ebe0e6e', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.25048234840d8ebe0e6e
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.25048234840d8ebe0e6e