homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'master_bedroom_humidifier'
        
    switch.25048234840d8ebe0e2f:
      <<: *customize
      hidden: true
    
    switch.master_bedroom_humidifier:
      <<: *customize
      friendly_name: "Master Bedroom Humidifier"

switch:
  - platform: template
    switches:
      backyard_amplifier:
        value_template: "{{ is_state('switch.25048234840d8ebe0e2f', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.25048234840d8ebe0e2f
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.25048234840d8ebe0e2f