homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'wood_grain_diffuser'
        
    fan.wood_grain_diffuser:
      <<: *customize
      friendly_name: "Wood Grain Diffuser"
    
    binary_sensor.wood_grain_diffuser_water_sensor:
      <<: *customize
      friendly_name: "Wood Grain Diffuser Water Sensor"

    light.wood_grain_diffuser_lamp:
      <<: *customize
      friendly_name: "Wood Grain Diffuser Lamp"

fan:
  - platform: mqtt
    name: wood_grain_diffuser
    availability_topic: "tele/woodgrain_diffuser/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "stat/woodgrain_woodgrain_diffuser/POWER1"
    command_topic: "cmnd/woodgrain_diffuser/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
    speed_state_topic: "tele/woodgrain_diffuser/STATE"
    speed_value_template: "{{ value_json.POWER2 }}"
    speed_command_topic: "cmnd/woodgrain_diffuser/POWER2"
    payload_low_speed: "OFF"
    payload_high_speed: "ON"
    qos: 1
    speeds:
      - low
      - high

binary_sensor:
  - platform: mqtt
    name: wood_grain_diffuser_water_sensor
    state_topic: "stat/woodgrain_diffuser/POWER4"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "tele/woodgrain_diffuser/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    device_class: problem

light:
  - platform: mqtt
    name: wood_grain_diffuser_lamp
    command_topic: "cmnd/woodgrain_diffuser/POWER3"
    state_topic: "tele/woodgrain_diffuser/STATE"
    state_value_template: "{% if value_json.Light is defined %}{{ value_json.Light }}{% endif %}"
    payload_on: "ON"
    payload_off: "OFF"
    brightness_command_topic: "cmnd/woodgrain_diffuser/DIMMER"
    brightness_state_topic: "tele/woodgrain_diffuser/STATE"
    brightness_scale: 100
    brightness_value_template: "{{ value_json.Dimmer }}"
    effect_command_topic: "cmnd/woodgrain_diffuser/EVENT"
    effect_state_topic: "tele/woodgrain_diffuser/STATE"
    effect_value_template: "{% if value_json.Light is defined %}{{ value_json.LightMode }}{% endif %}"
    effect_list:
      - rgb_cycle
      - color
      - white
    availability_topic: "tele/woodgrain_diffuser/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false
    rgb_command_topic: "cmnd/woodgrain_diffuser/TUYASEND3"
    rgb_command_template: "{% set brightness = state_attr('light.wood_grain_diffuser_lamp','brightness') | int %}{{ '8,%02x%02x%02xffff6464' | format(red, green, blue)}}"
    rgb_value_template: "{% if value_json.TuyaReceived is defined and value_json['TuyaReceived'].DpId == 8 %}{{ (value_json['TuyaReceived'].Type3Data[0:2]|int(base=16),value_json['TuyaReceived'].Type3Data[2:4]|int(base=16),value_json['TuyaReceived'].Type3Data[4:6]|int(base=16)) | join(',')}}{% endif %}"
    rgb_state_topic: "tele/woodgrain_diffuser/RESULT"