homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'wood_grain_diffuser'
        
    fan.wood_grain_diffuser:
      <<: *customize
      friendly_name: "Wood Grain Diffuser"
    
    binary_sensor.wood_grain_diffuser_water_sensor:
      <<: *customize
      friendly_name: "Wood Grain Diffuser Water Sensor"

    light.wood_grain_diffuser_lamp:
      <<: *customize
      friendly_name: "Wood Grain Diffuser Lamp"

# Tasmota Module Configuration
# https://templates.blakadder.com/oil_diffuser_550ml.html
# {"NAME":"MY-KCL01800FB","GPIO":[255,255,255,255,255,255,0,0,255,255,255,255,255],"FLAG":0,"BASE":54}
# Backlog SetOption66 1; TuyaMCU 21,7; TuyaMCU 11,111; TuyaMCU 12,101; TuyaMCU 13,133; TuyaMCU 14,9; TuyaMCU 15,115; DimmerRange 1,255; SetOption59 1; SwitchMode 1
# Rule1 ON TuyaReceived#Data=55AA00070005020400010012 do Power1 0 ENDON ON TuyaReceived#Data=55AA00070005020400010113 do Power1 1 ENDON ON TuyaReceived#Data=55AA00070005020400010214 do Power1 1 ENDON ON TuyaReceived#Data=55AA00070005020400010315 do TuyaSend4 2,1 ENDON ON Power1#State=1 do TuyaSend4 2,1 ENDON ON Power1#State=0 do TuyaSend4 2,0 ENDON
# Rule2 ON Power3#State=1 do backlog Tuyasend4 6,3; publish2 tele/woodgrain_diffuser/STATE {"Light":"ON","LightMode":"color"} ENDON ON Event#light_off do TuyaSend4 6,0 ENDON ON Event#rgb_cycle do TuyaSend4 6,1 ENDON ON Event#white do TuyaSend4 6,2 ENDON ON Event#color do TuyaSend4 6,3 ENDON ON Power3#State=0 do Backlog TuyaSend4 6,0; publish2 tele/woodgrain_diffuser/STATE {"Light":"OFF"} ENDON
# Rule3 ON TuyaReceived#Data=55AA00070005060400010319 do Power3 1 ENDON ON TuyaReceived#Data=55AA00070005060400010117 do Publish2 tele/woodgrain_diffuser/STATE {"Light":"ON","LightMode":"rgb_cycle"} ENDON ON TuyaReceived#Data=55AA00070005060400010016 do Power3 0 ENDON ON TuyaReceived#Data=55AA00070005060400010218 do Publish2 tele/woodgrain_diffuser/STATE {"Light":"ON","LightMode":"white"} ENDON

mqtt:
  fan:
    - name: wood_grain_diffuser
      availability_topic: "tele/woodgrain_diffuser/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "stat/woodgrain_diffuser/POWER1"
      command_topic: "cmnd/woodgrain_diffuser/POWER1"
      payload_on: "ON"
      payload_off: "OFF"
      qos: 1

  binary_sensor:
    - name: wood_grain_diffuser_water_sensor
      state_topic: "stat/woodgrain_diffuser/POWER4"
      payload_on: "ON"
      payload_off: "OFF"
      availability_topic: "tele/woodgrain_diffuser/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      qos: 1
      device_class: problem

  light:
    - name: wood_grain_diffuser_lamp
      command_topic: "cmnd/woodgrain_diffuser/POWER3"
      state_topic: "tele/woodgrain_diffuser/STATE"
      state_value_template: "{% if value_json.Light is defined %}{{ value_json.Light }}{% endif %}"
      payload_on: "ON"
      payload_off: "OFF"
      brightness_command_topic: "cmnd/woodgrain_diffuser/DIMMER"
      brightness_state_topic: "tele/woodgrain_diffuser/STATE"
      brightness_scale: 100
      brightness_value_template: "{{ value_json.Dimmer }}"
      effect_command_topic: "cmnd/woodgrain_diffuser/EVENT"
      effect_state_topic: "tele/woodgrain_diffuser/STATE"
      effect_value_template: "{% if value_json.Light is defined %}{{ value_json.LightMode }}{% endif %}"
      effect_list:
        - rgb_cycle
        - color
        - white
      availability_topic: "tele/woodgrain_diffuser/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      qos: 1
      retain: false
      rgb_command_topic: "cmnd/woodgrain_diffuser/TUYASEND3"
      rgb_command_template: "{% set brightness = state_attr('light.wood_grain_diffuser_lamp','brightness') | int %}{{ '8,%02x%02x%02xffff6464' | format(red, green, blue)}}"
      rgb_value_template: "{% if value_json.TuyaReceived is defined and value_json['TuyaReceived'].DpId == 8 %}{{ (value_json['TuyaReceived'].Type3Data[0:2]|int(base=16),value_json['TuyaReceived'].Type3Data[2:4]|int(base=16),value_json['TuyaReceived'].Type3Data[4:6]|int(base=16)) | join(',')}}{% endif %}"
      rgb_state_topic: "tele/woodgrain_diffuser/RESULT"