homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'skydrop'
        
    group.skydrop_sprinklers:
      <<: *customize

    sensor.active_sprinklers:
      <<: *customize
      friendly_name: Currently Active Sprinklers
      icon: mdi:sprinkler

    input_number.skydrop_4536a142_zone_3_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_4536a142_zone_3_watering','friendly_name') }} Total Minutes"
    input_number.skydrop_4536a142_zone_4_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_4536a142_zone_4_watering','friendly_name') }} Total Minutes"
    input_number.skydrop_4536a142_zone_5_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_4536a142_zone_5_watering','friendly_name') }} Total Minutes"
    input_number.skydrop_4536a142_zone_6_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_4536a142_zone_6_watering','friendly_name') }} Total Minutes"
    input_number.skydrop_4536a142_zone_7_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_4536a142_zone_7_watering','friendly_name') }} Total Minutes"
    input_number.skydrop_4536a142_zone_8_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_4536a142_zone_8_watering','friendly_name') }} Total Minutes"
    input_number.skydrop_d4d633de_zone_4_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_d4d633de_zone_4_watering','friendly_name') }} Total Minutes"
    input_number.skydrop_d4d633de_zone_5_total_minutes:
      <<: *customize
      friendly_name_template: "{{ state_attr('switch.skydrop_d4d633de_zone_5_watering','friendly_name') }} Total Minutes"

input_number:
  skydrop_4536a142_zone_3_total_minutes:
    min: 0
    max: 90
    step: 0.25
  skydrop_4536a142_zone_4_total_minutes:
    min: 0
    max: 90
    step: 0.25
  skydrop_4536a142_zone_5_total_minutes:
    min: 0
    max: 90
    step: 0.25
  skydrop_4536a142_zone_6_total_minutes:
    min: 0
    max: 90
    step: 0.25
  skydrop_4536a142_zone_7_total_minutes:
    min: 0
    max: 90
    step: 0.25
  skydrop_4536a142_zone_8_total_minutes:
    min: 0
    max: 90
    step: 0.25
  skydrop_d4d633de_zone_4_total_minutes:
    min: 0
    max: 90
    step: 0.25
  skydrop_d4d633de_zone_5_total_minutes:
    min: 0
    max: 90
    step: 0.25

group:
  skydrop_sprinklers:
    name: All Sprinklers
    entities:
      - switch.skydrop_4536a142_zone_3_watering
      - switch.skydrop_4536a142_zone_4_watering
      - switch.skydrop_4536a142_zone_5_watering
      - switch.skydrop_4536a142_zone_6_watering
      - switch.skydrop_4536a142_zone_7_watering
      - switch.skydrop_4536a142_zone_8_watering
      - switch.skydrop_d4d633de_zone_4_watering
      - switch.skydrop_d4d633de_zone_5_watering

sensor:
  - platform: template
    sensors:
      active_sprinklers:
        entity_id:
          - switch.skydrop_4536a142_zone_3_watering
          - switch.skydrop_4536a142_zone_4_watering
          - switch.skydrop_4536a142_zone_5_watering
          - switch.skydrop_4536a142_zone_6_watering
          - switch.skydrop_4536a142_zone_7_watering
          - switch.skydrop_4536a142_zone_8_watering
          - switch.skydrop_d4d633de_zone_4_watering
          - switch.skydrop_d4d633de_zone_5_watering
        value_template: >
          {% for obj in states|sort(attribute='last_updated',reverse=1) if obj.entity_id in state_attr('group.skydrop_sprinklers','entity_id') and obj.state == 'on' %}{{ obj.attributes.friendly_name|replace(' Watering','') }}{% if loop.index < loop.length %}, {% endif %}{% endfor %}