homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'back_door'
  
    binary_sensor.back_door:
      <<: *customize
      friendly_name: "Back Door"
      
    lock.kwikset_touchpad_electronic_deadbolt_locked:
      <<: *customize
      friendly_name: "Back Door Lock"