homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'garage_interior_door'
      
    binary_sensor.garage_interior_door:
      <<: *customize
      friendly_name: "Garage Interior Door"
