################################################################
## Packages / Garage Door
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'garage_door'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    light.x10_garage_door_relay:
      <<: *customize
      friendly_name: "Garage Door X10 Relay"
      hidden: true
      icon: mdi:light-switch
      
    switch.garage_door_button:
      <<: *expose
      friendly_name: "Garage Door"
      icon: mdi:light-switch
      
    script.garage_door_button_turn_on:
      <<: *expose
      friendly_name: "Garage Door"
      icon: mdi:light-switch
      
    binary_sensor.garage_door:
      <<: *customize
      friendly_name: "Garage Door Open?"
      
    cover.garage_door:
      <<: *customize
      friendly_name: "Garage Door"
      device_class: garage
      
    automation.garage_door_still_open:
      <<: *customize
      friendly_name: "Garage Door Open Alert"
      


light:
  - platform: x10rf
    devices:
      - id: b3
        name: x10_garage_door_relay
        
switch:
  - platform: template
    switches:
      garage_door_button:
        entity_id: light.x10_garage_door_relay
        value_template: "{{ false }}"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.garage_door_button_turn_on
        turn_off:
          service: logbook.log
          data_template:
            name: Garage Door Button
            message: is turned off
            entity_id: switch.garage_door_button
            domain: switch
            
script:
  garage_door_button_turn_on:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.x10_garage_door_relay
      - delay: '00:00:02'
      - service: homeassistant.turn_off
        data:
          entity_id: switch.garage_door_button
  garage_door_open_cover:
    sequence:
      - condition: template
        value_template: {{ state('sensor.garage_door_status') in ('closed','closing','stopped') }}
      - service: switch.turn_on
        data:
          entity_id: switch.garage_door_button
  garage_door_stop_cover:
    sequence:
      - condition: template
        value_template: {{ state('sensor.garage_door_position') not in ('0','100') }}
      - service: switch.turn_on
        data:
          entity_id: switch.garage_door_button
  garage_door_close_cover:
    sequence:
      - condition: template
        value_template: {{ state('sensor.garage_door_status') in ('open','opening','stopped') }}
      - service: switch.turn_on
        data:
          entity_id: switch.garage_door_button
        
            
binary_sensor:
  - platform: template
    sensors:
      garage_door:
        friendly_name: "Garage Door"
        device_class: garage_door
        value_template: "{{ states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 255 }}"
        
sensor:
  - platform: template
    sensors:
      garage_door_status:
        friendly_name: "Garage Door Status"
        value_template: >-
          {% if states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 255 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 2 %}
            opening
          {% elif states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 0 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 254 %}
            closing
          {% elif states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 0 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 2 %}
            closed
          {% elif states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 255 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 254 %}
            open
          {% endif %}
      garage_door_position:
        friendly_name: "Garage Door Position"
        value_template: >-
          {% if states('sensor.garage_door_status') == 'open' %}
            100
          {% elif states('sensor.garage_door_status') == 'closed' %}
            0
          {% else %}
            50
          {% endif %}
          
cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door"
        position_template: "{{ states('sensor.garage_door_position')|float }}"
        open_cover:
          service: script.garage_door_open_cover
        close_cover:
          service: script.garage_door_close_cover
        stop_cover:
          service: script.garage_door_stop_cover
        icon_template: >-
          {% if states('sensor.garage_door_position')|float > 0 %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
      
automation:

  - alias: "Garage Door Still Open"
    hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - cover.garage_door
        to: 'open'
        for: '00:00:10'
      - platform: state
        entity_id:
          - cover.garage_door
        to: 'open'
        for: '00:05:00'
      - platform: state
        entity_id:
          - cover.garage_door
        to: 'open'
        for: '00:15:00'
      - platform: state
        entity_id:
          - cover.garage_door
        to: 'open'
        for: '00:30:00'
    action:
      - service: camera.snapshot
        data_template:
          entity_id: "camera.yi_home_camera_garage"
          filename: "/tmp/yi_home_camera_garage_snapshot.jpg"
      - service: notify.nick
        data_template:
          message: "Garage door has been open for {{ relative_time(states.cover.garage_door.last_changed) }}"
          data:
            photo:
              caption: "Garage door has been open for {{ relative_time(states.cover.garage_door.last_changed) }}"
              file: "/tmp/yi_home_camera_garage_snapshot.jpg"
            inline_keyboard: 
              - 'Close garage:/close_garage'
      

  - alias: 'Telegram Command: close_garage'
    hide_entity: true
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/close_garage'
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'closing...'
      - service: cover.close_cover
        entity_id: cover.garage_door
          