homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'side_door'
      
    binary_sensor.side_door:
      <<: *customize
      friendly_name: "Side Door"
      
    sensor.side_door_unlocked_by_user_code:
      <<: *customize
      friendly_name: "Side door unlocked by user"

    lock.assa_abloy_yale_key_free_touchscreen_deadbolt_yrd446_locked:
      <<: *customize
      friendly_name: "Side Door Lock"

sensor:
  - platform: template
    sensors:
      side_door_unlocked_by_user_code:
        value_template: "{%if 'Unlocked with Keypad' in (state_attr('lock.assa_abloy_yale_key_free_touchscreen_deadbolt_yrd446_locked','lock_status') or '') %}{{ state_attr('lock.assa_abloy_yale_key_free_touchscreen_deadbolt_yrd446_locked','lock_status') | replace('Unlocked with Keypad by user','') | int }}{% endif %}"
