homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'internet_connection_status'
        
    binary_sensor.internet_connection_status:
      <<: *customize
      friendly_name: "Internet Connection Status"
        
    sensor.internet_connection_health_7d:
      <<: *customize
      friendly_name: "Internet Connection Health (7d)"
        
    sensor.internet_connection_downtime_24h:
      <<: *customize
      friendly_name: "Internet Connection Cumulative Downtime (24h)"
        
    sensor.internet_connection_downtime_7d:
      <<: *customize
      friendly_name: "Internet Connection Cumulative Downtime (7d)"
        
    sensor.internet_connection_disconnections_24h:
      <<: *customize
      friendly_name: "Internet Connectivity Lost (24h)"
        
    sensor.internet_connection_disconnections_7d:
      <<: *customize
      friendly_name: "Internet Connectivity Lost (7d)"
        
    binary_sensor.external_network_accessible:
      <<: *customize
      friendly_name: "External Network Accessible"
        
    binary_sensor.internal_network_accessible:
      <<: *customize
      friendly_name: "Internal Network Accessible"
        
binary_sensor:
  - platform: template
    sensors:
      internet_connection_status:
        device_class: connectivity
        value_template: >-
          {% set internal = is_state('binary_sensor.internal_network_accessible','on') %}
          {% set external = is_state('binary_sensor.external_network_accessible','on') %}
          {% if internal and external %}
          {{ true }}
          {% elif internal and not external %}
          {{ false }}
          {% elif not internal %}
          {{ None }}
          {% endif %}

sensor:
  - platform: history_stats
    name: internet_connection_health_7d
    entity_id: binary_sensor.internet_connection_status
    state: 'on'
    type: ratio
    start: '{{ as_timestamp(now()) - (7 * 86400) }}'  
    end: '{{ as_timestamp(now()) }}'
  - platform: history_stats
    name: internet_connection_downtime_24h
    entity_id: binary_sensor.internet_connection_status
    state: 'off'
    type: time
    start: '{{ as_timestamp(now()) - (1 * 86400) }}'  
    end: '{{ as_timestamp(now()) }}'
  - platform: history_stats
    name: internet_connection_downtime_7d
    entity_id: binary_sensor.internet_connection_status
    state: 'off'
    type: time
    start: '{{ as_timestamp(now()) - (7 * 86400) }}'  
    end: '{{ as_timestamp(now()) }}'
  - platform: history_stats
    name: internet_connection_disconnections_24h
    entity_id: binary_sensor.internet_connection_status
    state: 'off'
    type: count
    start: '{{ as_timestamp(now()) - (1 * 86400) }}'  
    end: '{{ as_timestamp(now()) }}'
  - platform: history_stats
    name: internet_connection_disconnections_7d
    entity_id: binary_sensor.internet_connection_status
    state: 'off'
    type: count
    start: '{{ as_timestamp(now()) - (7 * 86400) }}'  
    end: '{{ as_timestamp(now()) }}'
