homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'zwift'
        
    sensor.zwift_heartrate_803962:
      <<: *customize
      
    sensor.zwift_online_803962:
      <<: *customize
      
    sensor.zwift_speed_803962:
      <<: *customize
      
    sensor.zwift_cadence_803962:
      <<: *customize
      
    sensor.zwift_power_803962:
      <<: *customize
      
    sensor.zwift_altitude_803962:
      <<: *customize
    
    sensor.zwift_ftp_803962:
      <<: *customize
    
    sensor.zwift_power_zone_803962:
      <<: *customize
    
      
group:
  health_zwift:
    
    icon: mdi:bike
    name: Zwift - Nick
    entities:
      - sensor.zwift_online_803962
      - sensor.zwift_heart_rate_803962
      - sensor.zwift_speed_803962
      - sensor.zwift_power_803962
      - sensor.zwift_cadence_803962
      - sensor.zwift_gradient_803962
      - sensor.zwift_ftp_803962
      - sensor.zwift_power_zone_803962
      - automation.zwift_heartrate_fan_control

input_datetime:
  zwift_last_online_803962:
    name: Zwift Last Online
    has_date: true
    has_time: true
  zwift_last_offline_803962:
    name: Zwift Last Offline
    has_date: true
    has_time: true
    
automation:
  - alias: zwift_record_online_time
    trigger:
      - platform: state
        entity_id: sensor.zwift_online_803962
        to: "True"
        from: "False"
    condition: []
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zwift_last_online_803962
        data_template:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
          
  - alias: zwift_record_offline_time
    trigger:
      - platform: state
        entity_id: sensor.zwift_online_803962
        to: "False"
        from: "True"
    condition: []
    action:
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zwift_last_offline_803962
        data_template:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  - alias: zwift_heartrate_fan_control
    trigger:
      - platform: numeric_state
        entity_id: sensor.zwift_heart_rate_803962
        below: 100
      - platform: numeric_state
        entity_id: sensor.zwift_heart_rate_803962
        above: 100
        below: 120
      - platform: numeric_state
        entity_id: sensor.zwift_heart_rate_803962
        above: 120
        below: 140
      - platform: numeric_state
        entity_id: sensor.zwift_heart_rate_803962
        above: 140
    action:
      - service: fan.turn_on
        data_template:
          entity_id: fan.jasco_products_14287_fan_control_switch_level_2
          speed: >-
            {% set hr = states('sensor.zwift_heart_rate_803962') | int %}
            {% if hr <= 100 %}
            off
            {% elif hr > 100 and hr <= 120 %}
            low
            {% elif hr > 120 and hr <= 140 %}
            medium
            {% elif hr > 140 %}
            high
            {% endif %}

      
sensor:
  - platform: zwift
    username: !secret zwift_username
    password: !secret zwift_password
    
  - platform: template
    sensors:
      zwift_ftp_803962:
        friendly_name: "Zwift FTP (803962)"
        entity_id: sensor.zwift_online_803962
        unit_of_measurement: 'watts'
        value_template: "{{states.sensor.zwift_online_803962.attributes.ftp}}"
          
      zwift_power_zone_803962:
        friendly_name: "Zwift Power Zone (803962)"   
        entity_id: sensor.zwift_power_803962
        value_template: >-
          {% set ftp = states('sensor.zwift_ftp_803962') | float %}
          {% set power = states('sensor.zwift_power_803962') | float %}
          {% set zone1 = ftp | float * 0.55 %}
          {% set zone2 = ftp | float * 0.76 %}
          {% set zone3 = ftp | float * 0.90 %}
          {% set zone4 = ftp | float * 1.05 %}
          {% set zone5 = ftp | float * 1.2 %}
          {% set zone6 = ftp | float * 1.5 %}
          
          {% if power < 1 %}Off
          {% elif zone1 > power %}Active Recovery
          {% elif zone2 > power %}Endurance
          {% elif zone3 > power %}Tempo
          {% elif zone4 > power %}Threshold
          {% elif zone5 > power %}VO2 Max
          {% elif zone6 > power %}Anaerobic capacity
          {% elif zone6 < power %}Neuromuscular Power{% endif %}

  - platform: history_stats
    name: Threshold last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'Threshold'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'
          
  - platform: history_stats
    name: Off last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'Off'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'
          
  - platform: history_stats
    name: Active Recovery last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'Active Recovery'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'
          

  - platform: history_stats
    name: Endurance last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'Endurance'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'
          
  - platform: history_stats
    name: Tempo last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'Tempo'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'
          
  - platform: history_stats
    name: VO2 Max last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'VO2 Max'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'
          
  - platform: history_stats
    name: Anaerobic capacity last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'Anaerobic capacity'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'
          
  - platform: history_stats
    name: Neuromuscular Power last Zwift Session
    entity_id: sensor.zwift_power_zone_803962
    state: 'Neuromuscular Power'
    type: time
    start: '{{ states.input_datetime.zwift_last_online_803962.attributes.timestamp }}'  
    end: '{{ states.input_datetime.zwift_last_offline_803962.attributes.timestamp }}'