homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'tesla'

    climate.tesla_model_3_hvac_climate_system:
      <<: *customize

    lock.tesla_model_3_door_lock:
      <<: *customize

    lock.tesla_model_3_charger_door_lock:
      <<: *customize

    sensor.tesla_model_3_mileage_sensor:
      <<: *customize

    switch.tesla_model_3_update_switch:
      <<: *customize

    sensor.tesla_model_3_battery_sensor:
      <<: *customize

    switch.tesla_model_3_maxrange_switch:
      <<: *customize

    sensor.tesla_model_3_range_sensor:
      <<: *customize

    switch.tesla_model_3_charger_switch:
      <<: *customize

    sensor.tesla_model_3_temperature_sensor_inside:
      <<: *customize

    sensor.tesla_model_3_temperature_sensor_outside:
      <<: *customize

    binary_sensor.tesla_model_3_parking_brake_sensor:
      <<: *customize

    binary_sensor.tesla_model_3_charger_sensor:
      <<: *customize

    input_number.tesla_climate_target_temperature:
      <<: *customize

    script.tesla_climate_activate:
      <<: *customize
      friendly_name: Tesla Model 3 Climate Activator

tesla:
  username: !secret tesla_account_username
  password: !secret tesla_account_password 
  scan_interval: 600

input_number:
  tesla_climate_target_temperature:
    name: Tesla Model 3 Target Temperature
    icon: mdi:thermometer
    unit_of_measurement: "F"
    mode: slider
    step: 1
    min: 45
    max: 95

script:
  tesla_climate_activate:
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: automation.garage_door_open_when_interior_door_open
      - service: climate.set_temperature
        data_template:
          entity_id: climate.tesla_model_3_hvac_climate_system
          temperature: "{{ states('input_number.tesla_climate_target_temperature') | int  }}"
          hvac_mode: heat
      - service: climate.turn_on
        data:
          entity_id: climate.tesla_model_3_hvac_climate_system