homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'tesla'

tesla:
  username: !secret tesla_account_username
  password: !secret tesla_account_password 
  scan_interval: 600