substitutions:
  device_index: "01"
  device_name: amysen_wall_wart
  friendly_name: Amysen Wall Wart

esphome:
  name: ${device_name}_${device_index}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  domain: .twohunnid
  fast_connect: true

# Enable logging
logger:

web_server:
  port: 80

output:
- platform: gpio
  id: gpio_13
  inverted: True
  pin: GPIO13

light:
- platform: binary
  id: power_led
  name: "${friendly_name} ${device_index} Power LED"
  output: gpio_13
  effects:
    - strobe:
  
switch:
  - platform: gpio
    name: "${friendly_name} ${device_index}"
    icon: mdi:power-socket-us
    id: relay1
    pin:
      number: GPIO14
      inverted: False
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - light.turn_on: power_led
    on_turn_off:
    - light.turn_off: power_led

  - platform: restart
    name: "Reboot ${friendly_name} ${device_index}"
    id: reboot
    
binary_sensor:
  - platform: gpio
    id: power_button
    pin: 
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_press:
      then:
        - switch.toggle: relay1
    on_release:
      then:
        - switch.toggle: relay1
        
# Enable Home Assistant API
api:
  password: !secret ota_api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_api_password
