
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'confirm_alarm_upon_departure'
    
    automation.lock_all_doors_and_confirm_alarm_arming_when_nick_leaves:
      <<: *customize
      
    automation.telegram_command_arm_away:
      <<: *customize
      
      
automation:

  - alias: "Lock All Doors And Confirm Alarm Arming When Nick Leaves"
    trigger:
    - entity_id: input_boolean.presence_nick_homekit
      from: 'on'
      platform: state
      to: 'off'
      for: 00:00:30
    condition: []
    action:
    - service: lock.lock
      data:
        entity_id:
          - lock.kwikset_touchpad_electronic_deadbolt_locked
          - lock.kwikset_touchpad_electronic_deadbolt_locked_2
          - lock.assa_abloy_yale_key_free_touchscreen_deadbolt_yrd446_locked
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
    - service: notify.mobile_app_spacecell
      data_template:
        message: "Alarm has not been armed. Arm now?"
        data:
          push:
            category: yesno
          action_data:
            yes_script: "script.alarm_arm_away"
          