################################################################
## Packages / Living Room Television
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'televisions'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Package Items
    ################################################
    
    media_player.living_room_television:
      <<: *customize
      friendly_name: "Living Room Television"
      icon: mdi:television

    media_player.living_room_television_homekit:
      <<: *customize
      friendly_name: "Living Room Television (Homekit)"
      icon: mdi:television
      device_class: tv
      
    media_player.living_room_television_samsungtv:
      <<: *customize
      friendly_name: "Living Room Television - SamsungTV"
      icon: mdi:television
      
media_player:
  - platform: broadlink_media
    host: 192.168.1.168
    mac: '78:0f:77:18:5f:ae'
    name: living_room_television
    ping_host: 192.168.1.234
    ircodes_ini: 'lib/vpnmaster/homeassistant-custom-components/broadlink_media_codes/samsung.ini'
    timeout: 10
  - platform: universal
    name: living_room_television_homekit
    children:
      - media_player.living_room_television
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.living_room_television
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.living_room_television
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.living_room_television
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.living_room_television
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.living_room_television
      attributes:
        state: media_player.living_room_television
        source: media_player.living_room_television|source
        is_volume_muted: media_player.living_room_television|is_volume_muted
        source_list: media_player.living_room_television|source_list
