################################################################
## Packages / Living Room Television
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'televisions'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Package Items
    ################################################
    
    media_player.living_room_television:
      <<: *customize
      friendly_name: "Living Room Television"
      icon: mdi:television
      
    media_player.living_room_television_samsungtv:
      <<: *customize
      friendly_name: "Living Room Television - SamsungTV"
      icon: mdi:television
      
media_player:
  - platform: broadlink
    host: 192.168.1.199
    mac: '78:0f:77:18:5f:ae'
    name: living_room_television
    ping_host: 192.168.1.109
    ircodes_ini: 'lib/vpnmaster/homeassistant-custom-components/broadlink_media_codes/samsung.ini'
    timeout: 10
  - platform: samsungtv
    host: 192.168.1.109
    port: 8002
    mac: 38:01:95:7B:A3:98
    name: living_room_television_samsungtv
    encrypted_config: ~/.homeassistant/samsungtv.config
