################################################################
## Packages / Living Room Television
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'televisions'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Package Items
    ################################################
    
    media_player.living_room_television:
      <<: *customize
      friendly_name: "Living Room Television"
      icon: mdi:television

    media_player.living_room_television_homekit:
      <<: *customize
      friendly_name: "Living Room Television (Homekit)"
      icon: mdi:television
      device_class: tv
      
    media_player.samsung_7_series_75:
      <<: *customize
      friendly_name: "Living Room Television - SamsungTV"
      icon: mdi:television
      
media_player:
  - platform: smartir
    controller_data: remote.living_room_rm_mini_remote
    name: living_room_television
    device_code: 1060
    power_sensor: media_player.samsung_7_series_75
  - platform: universal
    name: living_room_television_homekit
    children:
      - media_player.living_room_television
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.living_room_television
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.samsung_7_series_75
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.samsung_7_series_75
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.samsung_7_series_75
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.samsung_7_series_75
    attributes:
      state: media_player.living_room_television
      source: media_player.living_room_television|source
      is_volume_muted: media_player.living_room_television|is_volume_muted
      source_list: media_player.living_room_television|source_list
