homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'master_bedroom_television'

    media_player.master_bedroom_television:
      <<: *customize
      friendly_name: "Master Bedroom Television"
      ir_codes_source: http://www.remotecentral.com/cgi-bin/mboard/rc-discrete/thread.cgi?7222
      icon: mdi:television
      device_class: tv

    media_player.master_bedroom_television_homekit:
      <<: *customize
      friendly_name: "Master Bedroom Television (Homekit)"
      icon: mdi:television
      device_class: tv
      
    automation.turn_on_master_bedroom_tv_if_fire_tv_stick_is_on:
      <<: *customize
      friendly_name: "Turn On Master Bedroom TV if Fire TV Stick is On"
      
    automation.turn_off_master_bedroom_tv_if_fire_tv_stick_is_off:
      <<: *customize
      friendly_name: "Turn Off Master Bedroom TV if Fire TV Stick is Off"
      
media_player:
  - platform: smartir
    controller_data: remote.master_bedroom_rm_mini_remote
    name: master_bedroom_television
    device_code: 1400
  - platform: universal
    name: master_bedroom_television_homekit
    children:
      - media_player.master_bedroom_television
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.master_bedroom_television
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.master_bedroom_television
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.master_bedroom_television
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.master_bedroom_television
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.master_bedroom_television
    attributes:
      state: media_player.master_bedroom_television
      source: media_player.master_bedroom_television|source
      is_volume_muted: media_player.master_bedroom_television|is_volume_muted
      source_list: media_player.master_bedroom_television|source_list

automation:
  - alias: turn_on_master_bedroom_tv_if_fire_tv_stick_is_on
    id: turn_on_master_bedroom_tv_if_fire_tv_stick_is_on
    trigger: 
    - platform: state
      entity_id: media_player.nicholas_s_4th_fire_tv_2
      from: 'off'
    condition: []
    action:
    - service: homeassistant.turn_on
      data:
        entity_id: media_player.master_bedroom_television
    - delay: 00:00:03
    - service: media_player.select_source
      data:
        entity_id: media_player.master_bedroom_television
        source: Input 4
      
  - alias: turn_off_master_bedroom_tv_if_fire_tv_stick_is_off
    id: turn_off_master_bedroom_tv_if_fire_tv_stick_is_off
    trigger: 
    - platform: state
      entity_id: media_player.nicholas_s_4th_fire_tv_2
      to: 'off'
    condition: []
    action:
    - service: homeassistant.turn_off
      data:
        entity_id: media_player.master_bedroom_television