homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'manual_alarm'
      
    alarm_control_panel.home_alarm:
      <<: *customize

alarm:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_panel_code
    pending_time: 30
    delay_time: 15
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_night:
      pending_time: 5