homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'manual_alarm'
      
    alarm_control_panel.home_alarm:
      <<: *customize

    input_boolean.home_alarm_test_mode:
      <<: *customize
      friendly_name: "Home Alarm Testing Mode"



alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_panel_code
    arming_time: 20
    delay_time: 15
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 20
      delay_time: 0
    armed_night:
      arming_time: 20

  - platform: template
    panels:
      home_alarm_no_code:
        code_arm_required: false
        value_template: "{{ states('alarm_control_panel.home_alarm') }}"
        arm_away:
          service: alarm_control_panel.alarm_arm_away
          data:
            entity_id: alarm_control_panel.home_alarm
            code: !secret alarm_panel_code
        arm_home:
          service: alarm_control_panel.alarm_arm_home
          data:
            entity_id: alarm_control_panel.home_alarm
            code: !secret alarm_panel_code
        arm_night:
          service: alarm_control_panel.alarm_arm_night
          data:
            entity_id: alarm_control_panel.home_alarm
            code: !secret alarm_panel_code
        disarm:
          - service: alarm_control_panel.alarm_disarm
            data:
              entity_id: alarm_control_panel.home_alarm
              code: !secret alarm_panel_code

input_boolean:
  home_alarm_test_mode:
    icon: mdi:alarm

script:

  trigger_alarm_with_warning:
    sequence:
      - service: script.alexa_announcement_all
        data:
          message: The alarm has been triggered. Siren will start in less than 30 seconds.
      - service: notify.ios_nickcell
        data:
          title: "Home alarm triggered!"
          message: The alarm has been triggered. Siren will start in less than 30 seconds. Disarm?
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0
              category: yesno
            action_data:
              yes_script: "script.alarm_disarm"
      - service: alarm_control_panel.alarm_trigger
        data:
          entity_id: alarm_control_panel.home_alarm

  unexpected_motion_ask_to_trigger:
    sequence:
      - service: notify.ios_nickcell
        data_template:
          title: "Unexpected motion detected!"
          message: &motion_detected_message >
            Unexpected motion detected! Do you wish to trigger the alarm?
            {% for obj in states|sort(attribute='last_updated',reverse=1) if obj.entity_id in state_attr('group.all_interior_motion_sensors','entity_id') and obj.state == 'on' %}{{ obj.attributes.friendly_name|replace('Motion - ','') }} ({{ (now() - obj.last_updated).total_seconds()|int }}s ago){% if loop.index < loop.length %}, {% endif %}{% endfor %}
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0
              category: yesno
            action_data:
              yes_script: "script.trigger_alarm_with_warning"

  alarm_triggered:
    sequence:
      - service: notify.ios_nickcell
        data:
          title: "Home alarm siren activated!"
          message: The alarm siren has been activated! Disarm?
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0
              category: yesno
            action_data:
              yes_script: "script.alarm_disarm"
      - service: script.alarm_alexa_is_a_snitch_start
      - condition: state
        entity_id: input_boolean.home_alarm_test_mode
        state: 'off'
      - service: homeassistant.turn_on
        data:
          entity_id: switch.linear_wa105dbz1_main_operated_siren_switch
      - service: homeassistant.turn_on
        data:
          entity_id: switch.konnected_alarm_bell
      - service: homeassistant.turn_on
        data:
          entity_id: switch.noonlight_switch
      - service: homeassistant.turn_on
        data:
          entity_id: script.front_porch_lights_alarm_mode_on

  alarm_untriggered:
    sequence:
      - data:
          entity_id: switch.linear_wa105dbz1_main_operated_siren_switch
        service: homeassistant.turn_off
      - data:
          entity_id: switch.konnected_alarm_bell
        service: homeassistant.turn_off
      - service: light.turn_on
        data:
          effect: white
        entity_id: light.front_porch_lights
  
  alarm_alexa_is_a_snitch_start:
    sequence:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: triggered
      - delay: 00:00:01
      - service: script.alarm_alexa_is_a_snitch

  alarm_alexa_is_a_snitch:
    sequence:
      - service: script.alexa_announcement_all
        data:
          message: The police have been notified. Leave the premises immediately!
      - delay: 00:00:15
      - service: script.alarm_alexa_is_a_snitch_start

  front_porch_lights_alarm_mode_on:
    alias: Front Porch Lights Alarm Mode On
    sequence:
    - data:
        effect: 5
      entity_id: light.front_porch_right
      service: light.turn_on
    - data:
        effect: 7
      entity_id: light.front_porch_left
      service: light.turn_on

  alarm_arm_night:
    alias: 'Alarm: Arm Night'
    sequence:
    - data:
        entity_id: alarm_control_panel.home_alarm
        code: !secret alarm_panel_code
      service: alarm_control_panel.alarm_arm_night

  alarm_arm_away:
    alias: 'Alarm: Arm Away'
    sequence:
    - data:
        entity_id: alarm_control_panel.home_alarm
        code: !secret alarm_panel_code
      service: alarm_control_panel.alarm_arm_away

  alarm_arm_home:
    alias: 'Alarm: Arm Home'
    sequence:
    - data:
        entity_id: alarm_control_panel.home_alarm
        code: !secret alarm_panel_code
      service: alarm_control_panel.alarm_arm_home

  alarm_disarm:
    alias: 'Alarm: Disarm'
    sequence:
    - data:
        entity_id: alarm_control_panel.home_alarm
        code: !secret alarm_panel_code
      service: alarm_control_panel.alarm_disarm



automation:
  - alias: Alarm trigger when doors open
    trigger:
    - entity_id:
      - binary_sensor.back_door
      - binary_sensor.side_door
      - binary_sensor.garage_interior_door
      - binary_sensor.front_door
      platform: state
      to: 'on'
    condition:
    - condition: template
      value_template: "{{ states('alarm_control_panel.home_alarm') in ('armed_away','armed_night') }}"
    action:
    - service: script.trigger_alarm_with_warning

  - alias: Alarm trigger when garage door opens at night
    trigger:
    - above: '0'
      entity_id: sensor.garage_door_position
      for: 00:00:01
      platform: numeric_state
    condition:
    - condition: template
      value_template: "{{ states('alarm_control_panel.home_alarm') in ('armed_night') }}"
    action:
    - service: script.trigger_alarm_with_warning

  - alias: Ask to trigger alarm when motion detected at night
    trigger:
    - entity_id: 
      - binary_sensor.motion_indoor_foyer
      - binary_sensor.modetftp_motion_laundry
      - binary_sensor.konnected_motion_kitchen
      from: 'off'
      platform: state
      to: 'on'
    condition:
    - condition: template
      value_template: "{{ states('alarm_control_panel.home_alarm') in ('armed_night') }}"
    action:
    - service: script.unexpected_motion_ask_to_trigger

  - alias: Alarm triggered
    trigger:
    - entity_id: alarm_control_panel.home_alarm
      platform: state
      to: triggered
    condition: []
    action:
    - service: script.alarm_triggered

  - alias: Alarm triggered stop
    trigger:
    - entity_id: alarm_control_panel.home_alarm
      from: triggered
      platform: state
    condition: []
    action:
    - service: script.alarm_untriggered

  - alias: Disable alarm test mode after 10 minutes
    trigger:
      - platform: state
        entity_id: input_boolean.home_alarm_test_mode
        to: 'on'
        for: 00:10:00
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.home_alarm_test_mode