homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'ballet_studio_lamp'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.ballet_studio_lamp:
      <<: *customize
      friendly_name: "Ballet Studio Lamp"


automation:
  - id: ballet_studio_lamp_double_tap_on
    alias: Ballet Studio Lamp On When Double Tap Wall Switch On
    description: ''
    trigger:
    - event_data:
        entity_id: zwave.z_wave_products_inc_wd100_3
        scene_data: 7860
        scene_id: 1
      event_type: zwave.scene_activated
      platform: event
    condition: []
    action:
    - entity_id: light.ballet_studio_lamp
      service: light.turn_on
  - id: ballet_studio_lamp_double_tap_off
    alias: Ballet Studio Lamp Off When Double Tap Wall Switch Off
    description: ''
    trigger:
    - event_data:
        entity_id: zwave.z_wave_products_inc_wd100_3
        scene_data: 7860
        scene_id: 2
      event_type: zwave.scene_activated
      platform: event
    condition: []
    action:
    - entity_id: light.ballet_studio_lamp
      service: light.turn_off

light:
  - platform: mqtt
    name: ballet_studio_lamp
    optimistic: false
    on_command_type: first
    command_topic: "x10/b1/command"
    payload_on: "fon"
    payload_off: "foff"    
    state_topic: "x10/b1/status"
    state_value_template: "f{{ value }}"
    brightness_command_topic: "x10/b1/fbrightness"
    brightness_state_topic: "x10/b1/status/brightness"