homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'ballet_studio_lights'
    
    light.zwaveproducts_com_wd_100_level_2:
      <<: *customize
      friendly_name: "Ballet Studio Lights"
        