homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'christmas_eave_lights'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.holiday_lighting_south:
      <<: *customize
      friendly_name: "Holiday Lighting - South"
      
    light.holiday_lighting_north:
      <<: *customize
      friendly_name: "Holiday Lighting - North"
      
    light.christmas_eave_lights:
      <<: *customize
      friendly_name: "Christmas Eave Lights"

light:
  - platform: switch
    name: holiday_lighting_south
    entity_id: switch.holiday_lighting_south_outlet
  - platform: switch
    name: holiday_lighting_north
    entity_id: switch.sonoff_mini_01
  - platform: group
    name: christmas_eave_lights
    entities:
      - light.holiday_lighting_south
      - light.holiday_lighting_north