homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'christmas_tree'
        
    light.remotec_unknown_type_8200_id_8130_level_2:
      <<: *customize
      hidden: true
    
    light.christmas_tree:
      <<: *customize
      friendly_name: "Christmas Tree"

light:
  - platform: template
    lights:
      christmas_tree:
        value_template: "{{ is_state('light.remotec_unknown_type_8200_id_8130_level_2', 'on') }}"
        level_template: "{{ state_attr('light.remotec_unknown_type_8200_id_8130_level_2','brightness')|int }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.remotec_unknown_type_8200_id_8130_level_2
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.remotec_unknown_type_8200_id_8130_level_2
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.remotec_unknown_type_8200_id_8130_level_2
            brightness: "{{ brightness }}"