homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'copper_wire_string_lights'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    switch.rm_mini_copper_wire_string_lights:
      hidden: true
    
    light.copper_wire_string_lights:
      <<: *expose
      friendly_name: "Copper Wire String Lights"
      comm_protocol: "infrared"
      
input_select:
  copper_wire_string_lights_mode:
    name: Copper Wire String Lights Mode
    options:
      - Combination
      - In wave
      - Sequential
      - Slo glo
      - Chasing flash
      - Slow Fade
      - Twinkle/Flash
      - Steady on
      
group:
  copper_wire_string_lights_settings:
    name: Copper Wire String Lights Settings
    entities:
      - light.copper_wire_string_lights
      - input_select.copper_wire_string_lights_mode
      
automation:
  - alias: Copper Wire String Lights Mode Changed
    trigger:
      platform: state
      entity_id: input_select.copper_wire_string_lights_mode
    action:
      - service: homeassistant.turn_on
        entity_id: light.copper_wire_string_lights
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.copper_wire_string_lights_mode", "Combination") %}
            script.rm_mini_copper_wire_string_lights_button_1
            {% elif is_state("input_select.copper_wire_string_lights_mode", "In wave") %}
            script.rm_mini_copper_wire_string_lights_button_2
            {% elif is_state("input_select.copper_wire_string_lights_mode", "Sequential") %}
            script.rm_mini_copper_wire_string_lights_button_3
            {% elif is_state("input_select.copper_wire_string_lights_mode", "Slo glo") %}
            script.rm_mini_copper_wire_string_lights_button_4
            {% elif is_state("input_select.copper_wire_string_lights_mode", "Chasing flash") %}
            script.rm_mini_copper_wire_string_lights_button_5
            {% elif is_state("input_select.copper_wire_string_lights_mode", "Slow Fade") %}
            script.rm_mini_copper_wire_string_lights_button_6
            {% elif is_state("input_select.copper_wire_string_lights_mode", "Twinkle/Flash") %}
            script.rm_mini_copper_wire_string_lights_button_7
            {% elif is_state("input_select.copper_wire_string_lights_mode", "Steady on") %}
            script.rm_mini_copper_wire_string_lights_button_8
            {% else %}
            none
            {% endif %}

        
light:
  - platform: template
    lights:
      copper_wire_string_lights:
        value_template: '{{ is_state("switch.rm_mini_copper_wire_string_lights", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.rm_mini_copper_wire_string_lights
        turn_off:
          service: script.turn_on
          entity_id: script.rm_mini_copper_wire_string_lights_button_off
        
script:
  rm_mini_copper_wire_string_lights_button_1:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABKpQTEhMTFRAUERMTFBISExISEzcUNhM2EjcUNhM3FDYSNxUSEhEUNxMSEhMTExI3ExIUNhM2ExMSNxM3EzYUEhQ1EwAFHgABKkoSAAxUAAErShIADQU="
  rm_mini_copper_wire_string_lights_button_2:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBQAAABLJIVERQRFBEVERQRFBEVERQRFDUVNRQ2FDUVNRQ2FDUUNhQ1FTUUERURFBEUERU1FBEUERQSFDUUNhU1FDUUEhQ1FQAFHQABKkoUAA0FAAAAAAAAAAA="
  rm_mini_copper_wire_string_lights_button_3:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLJIVERMSFBEVEhISExIVERMSEzcUNRM3FDYUNRU1EzcVNBQ2FDYTNhURFBEUERURExIUERQSFRATNxQ1FDYTNxQ1FAAFHgABLEkTAAxTAAEsSRQADQU="
  rm_mini_copper_wire_string_lights_button_4:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLJIVERQRFBIUERQRFBIUERQREzcUNRU1FDYUNRQ2FDYUNRQ2FBEUERU1FBEVERQRFBEVERM2FTUUERU1FDYUNRQ2FAAFHgABLEgUAAxSAAEsSBUADQU="
  rm_mini_copper_wire_string_lights_button_5:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLJMUERQSFBEUERQRFRETEhQRFTUUNhQ1FTUVNRQ1FTUUNhQRFDYUNRURFDUUEhQRFBEVNRQRFBEVNRQRFDYUNRU1FAAFHgABK0gUAAxTAAEsSBQADQU="
  rm_mini_copper_wire_string_lights_button_6:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLJMUERQRExMUERQRFBIUERQRFTUUNRQ2FDUVNRQ2FDUUNhQ1FRETNhQ2ExIUERURFBEUERQ2FBEUERU1FDYUNRQ2FAAFHQABLEgUAAxSAAErSBUADQU="
  rm_mini_copper_wire_string_lights_button_7:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLZIUERURFRAUERYQExIWEBUQEzcUNRQ2FDYVNBQ2FDUVNRURFBEUNhQ1FREVEBURFRATNxQ1FBIUERM3EzYUNhQ2FAAFHQABK0kWAAxQAAEsSBUADQU="
  rm_mini_copper_wire_string_lights_button_8:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLJMUERQSFBEUERQSFBEVEBURFDUVNRQ2FDUVNRQ2FDQWNRQSFDUVNRQ2FDUVERU1FBEVNRQRFREUERUQFTUUEhQ1FQAFHQABLUgVAAxRAAErSRQADQU="
  rm_mini_copper_wire_string_lights_button_dim_up:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLpMVERQRFREUERURFBEVERQRFTUUNRU1FDYUNhQ1FTUVNRQSFDUUEhQ1FTUVERQ1FREUNhQRFTUUERURFDYUERU1FAAFHgABLUkUAAxSAAEsRxQADQU="
  rm_mini_copper_wire_string_lights_button_dim_down:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_199
        data:
          packet: "JgBYAAABLZIUEhQRFBEVERQRFBEVERMSFDYTNhQ2FDYUNRQ2FDYUNRURFBEUERU1FBEVERMSFREUNRU1FDYUERU1FDYUNRU1FAAFHQABLUgVAAxRAAEsSBQADQU="
  rm_mini_copper_wire_string_lights_button_off:
    sequence:
      - service: homeassistant.turn_off
        entity_id: switch.rm_mini_copper_wire_string_lights
      - service: homeassistant.turn_off
        entity_id: switch.rm_mini_copper_wire_string_lights
  rm_mini_copper_wire_string_lights_button_on:
    sequence:
      - service: homeassistant.turn_on
        entity_id: switch.rm_mini_copper_wire_string_lights
      - service: homeassistant.turn_on
        entity_id: switch.rm_mini_copper_wire_string_lights