homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'dining_room_chandelier'
    
    light.zwaveproducts_com_wd_100_level:
      <<: *customize
      friendly_name: "Dining Room Chandelier"
        