homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'front_yard_holiday_lights'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.olive_tree_holiday_lights:
      <<: *customize
      friendly_name: "Olive Tree Holiday Lights"
      source_switch: switch.front_olive_tree_outlet
      
    light.ash_tree_holiday_lights:
      <<: *customize
      friendly_name: "Ash Tree Holiday Lights"
      source_switch: switch.front_ash_tree_outlet
      
    light.front_pine_tree_holiday_lights:
      <<: *customize
      friendly_name: "Front Pine Holiday Lights"
      source_switch: switch.driveway_gate_outlet
      
    light.north_front_yard_holiday_lights:
      <<: *customize
      friendly_name: "North Front Yard Holiday Lights"
      source_switch: switch.north_driveway_gate_outlet_switch
      
    light.holiday_lighting_south:
      <<: *customize
      friendly_name: "Holiday Lighting - South"
      source_switch: switch.holiday_lighting_south_outlet

    light.holiday_lighting_north:
      <<: *customize
      friendly_name: "Holiday Lighting - North"
      source_switch: switch.holiday_lighting_north_outlet

    light.holiday_lighting_central:
      <<: *customize
      friendly_name: "Holiday Lighting - Central"
      source_switch: switch.holiday_lighting_central_outlet
      
    light.christmas_eave_lights:
      <<: *customize
      friendly_name: "Christmas Eave Lights"

light:
  - platform: template
    lights:
      olive_tree_holiday_lights:
        unique_id: olive_tree_holiday_lights
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.front_olive_tree_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.front_olive_tree_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.front_olive_tree_outlet

      ash_tree_holiday_lights:
        unique_id: ash_tree_holiday_lights
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.front_ash_tree_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.front_ash_tree_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.front_ash_tree_outlet

      front_pine_tree_holiday_lights:
        unique_id: front_pine_tree_holiday_lights
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.driveway_gate_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.driveway_gate_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.driveway_gate_outlet

      north_front_yard_holiday_lights:
        unique_id: north_front_yard_holiday_lights
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.north_driveway_gate_outlet_switch", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.north_driveway_gate_outlet_switch
        turn_off:
          service: switch.turn_off
          entity_id: switch.north_driveway_gate_outlet_switch

      holiday_lighting_south:
        unique_id: holiday_lighting_south
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.holiday_lighting_south_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.holiday_lighting_south_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.holiday_lighting_south_outlet

      holiday_lighting_north:
        unique_id: holiday_lighting_north
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.holiday_lighting_north_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.holiday_lighting_north_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.holiday_lighting_north_outlet

      holiday_lighting_central:
        unique_id: holiday_lighting_central
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.holiday_lighting_central_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.holiday_lighting_central_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.holiday_lighting_central_outlet

  - platform: group
    name: christmas_eave_lights
    entities:
      - light.holiday_lighting_south
      - light.holiday_lighting_central
      - light.holiday_lighting_north