homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'front_yard_holiday_lights'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.olive_tree_holiday_lights:
      <<: *customize
      friendly_name: "Olive Tree Holiday Lights"
      
    light.ash_tree_holiday_lights:
      <<: *customize
      friendly_name: "Ash Tree Holiday Lights"
      
    light.front_pine_tree_holiday_lights:
      <<: *customize
      friendly_name: "Front Pine Holiday Lights"
      
    light.holiday_lighting_south:
      <<: *customize
      friendly_name: "Holiday Lighting - South"
      
    light.holiday_lighting_north:
      <<: *customize
      friendly_name: "Holiday Lighting - North"
      
    light.christmas_eave_lights:
      <<: *customize
      friendly_name: "Christmas Eave Lights"

light:
  - platform: template
    lights:
      olive_tree_holiday_lights:
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.front_olive_tree_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.front_olive_tree_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.front_olive_tree_outlet

      ash_tree_holiday_lights:
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.front_ash_tree_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.front_ash_tree_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.front_ash_tree_outlet

      front_pine_tree_holiday_lights:
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.driveway_gate_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.driveway_gate_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.driveway_gate_outlet

      holiday_lighting_south:
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.holiday_lighting_south_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.holiday_lighting_south_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.holiday_lighting_south_outlet

      holiday_lighting_north:
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.sonoff_mini_01", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.sonoff_mini_01
        turn_off:
          service: switch.turn_off
          entity_id: switch.sonoff_mini_01
          
  - platform: group
    name: christmas_eave_lights
    entities:
      - light.holiday_lighting_south
      - light.holiday_lighting_north