homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'garage_overhead_light'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.garage_overhead_light:
      <<: *customize
      friendly_name: "Garage Overhead Light"

light:
  - platform: mqtt
    name: garage_overhead_light
    optimistic: false
    command_topic: "x10/b9/command"
    payload_on: "on"
    payload_off: "off"
    state_topic: "x10/b9/status"
    state_value_template: "{{ value }}"
    