homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'garage_overhead_light'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.garage_overhead_light:
      <<: *customize
      friendly_name: "Garage Overhead Light"

light:
  - platform: x10rf
    devices:
      - id: b9
        name: garage_overhead_light
    