homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'master_bathroom_light'
      hide: &hide
        <<: *customize
        hidden: true
    
    light.jasco_products_26933_smart_motion_dimmer_level:
      <<: *hide
    
    light.jasco_products_26933_smart_motion_dimmer_level_2:
      <<: *hide
    
    sensor.jasco_products_26933_smart_motion_dimmer_burglar:
      <<: *hide
      
    sensor.jasco_products_26933_smart_motion_dimmer_burglar_2:
      <<: *hide
      
    light.master_bathroom_light:
      <<: *customize
      
    binary_sensor.master_bathroom_motion:
      <<: *customize
      
binary_sensor:
  - platform: template 
    sensors:
      master_bathroom_motion:
        friendly_name: "Motion - Master Bathroom"
        device_class: motion
        value_template: "{{ states('sensor.jasco_products_26933_smart_motion_dimmer_burglar')|int == 8 }}"

light:
  - platform: template
    lights:
      master_bathroom_light:
        friendly_name: "Master Bathroom Light"
        level_template: "{{ state_attr('light.jasco_products_26933_smart_motion_dimmer_level_2','brightness')|int }}"
        value_template: "{{ states('light.jasco_products_26933_smart_motion_dimmer_level_2') }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.jasco_products_26933_smart_motion_dimmer_level_2
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.jasco_products_26933_smart_motion_dimmer_level_2
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.jasco_products_26933_smart_motion_dimmer_level_2
            brightness: "{{ brightness }}"
    