homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'office_desk_lamp'
        
    switch.25048234840d8ebdd2c2:
      <<: *customize
      hidden: true
    
    light.office_desk_lamp:
      <<: *customize
      friendly_name: "Office Desk Lamp"

light:
  - platform: template
    lights:
      office_desk_lamp:
        value_template: "{{ is_state('switch.25048234840d8ebdd2c2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.25048234840d8ebdd2c2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.25048234840d8ebdd2c2