homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'olive_tree_holiday_lights'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.olive_tree_holiday_lights:
      <<: *customize
      friendly_name: "Olive Tree Holiday Lights"

light:
  - platform: template
    lights:
      olive_tree_holiday_lights:
        availability_template: "{{ is_state('group.holiday_modes','on') }}"
        value_template: '{{ is_state("switch.front_olive_tree_outlet", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.front_olive_tree_outlet
        turn_off:
          service: switch.turn_off
          entity_id: switch.front_olive_tree_outlet