homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'pantry_light'
    
    light.pantry_light:
      <<: *customize
      hidden: true
      friendly_name: "Pantry Light (Actual)"
      
    switch.reboot_pantry_light_sonoff:
      <<: *customize
      
    binary_sensor.pantry_door_sensor:
      <<: *customize
      
    light.pantry_light_conditional:
      <<: *customize
      friendly_name: "Pantry Light"
      
    script.pantry_light_on_only_if_door_open:
      <<: *customize
      
script:
  pantry_light_on_only_if_door_open:
    sequence:
      - condition: state
        entity_id: binary_sensor.pantry_door_sensor
        state: on
      - service: light.turn_on
        data:
          entity_id: light.pantry_light

light:
  - platform: template
    lights:
      pantry_light_conditional:
        value_template: "{{ states.light.pantry_light.state }}"
        turn_on:
          service: script.pantry_light_on_only_if_door_open
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.pantry_light