homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_room_lamp'
        
    light.remotec_unknown_type_8200_id_8130_level:
      <<: *customize
      hidden: true
    
    light.plant_room_lamp:
      <<: *customize
      friendly_name: "Plant Room Lamp"

light:
  - platform: template
    lights:
      plant_room_lamp:
        value_template: "{{ is_state('light.remotec_unknown_type_8200_id_8130_level', 'on') }}"
        level_template: "{{ state_attr('light.remotec_unknown_type_8200_id_8130_level','brightness')|int }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.remotec_unknown_type_8200_id_8130_level
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.remotec_unknown_type_8200_id_8130_level
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.remotec_unknown_type_8200_id_8130_level
            brightness: "{{ brightness }}"