homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_room_lamp'

automation:
  - id: '1580152626963'
    alias: Plant Room Lamp On When Double Tap Wall Switch On
    description: ''
    trigger:
    - event_data:
        entity_id: zwave.zwaveproducts_com_wd_100_4
        scene_data: 7860
        scene_id: 1
      event_type: zwave.scene_activated
      platform: event
    condition: []
    action:
    - entity_id: light.plant_room_lamp
      service: light.turn_on
  - id: '1580153067349'
    alias: Plant Room Lamp Off When Double Tap Wall Switch Off
    description: ''
    trigger:
    - event_data:
        entity_id: zwave.zwaveproducts_com_wd_100_4
        scene_data: 7860
        scene_id: 2
      event_type: zwave.scene_activated
      platform: event
    condition: []
    action:
    - entity_id: light.plant_room_lamp
      service: light.turn_off