homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_room_lights'
    
    light.zwaveproducts_com_wd_100_level_3:
      <<: *customize
      friendly_name: "Plant Room Lights"

    sensor.plant_room_lights_on_today:
      <<: *customize
      friendly_name: "Plant Room Light Duration Tracker"

sensor:
  - platform: history_stats
    name: plant_room_lights_on_today
    entity_id: light.zwaveproducts_com_wd_100_level_3
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'