homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'string_lights'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.string_lights:
      <<: *customize
      friendly_name: "String Lights"

light:
  - platform: mqtt
    name: string_lights
    command_topic: "x10/b2/command"
    payload_on: "fon"
    payload_off: "foff"
    