homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'string_lights'
      hide: &hide
        <<: *customize
        hidden: true
      
    light.string_lights:
      <<: *customize
      friendly_name: "String Lights"
    