substitutions:
  device_name: driveway_swing_gate_controller

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini_pro
  board_flash_mode: dout
  restore_from_flash: true

wifi:
  reboot_timeout: 180s
  networks:
  - ssid: !secret wifi_primary_ssid
    password: !secret wifi_primary_password
  - ssid: !secret wifi_secondary_ssid
    password: !secret wifi_secondary_password
  ap:
    ssid: driveway_swing_gate_AP

captive_portal:

api:
  encryption:
    key: gnyJOFz8/nbevejcDuAq2vGu5GQIyCOfu9VwWJQoicw=
  reboot_timeout: 0s

ota:
  - platform: esphome
    id: ha_ota
    password: !secret ota_api_password

logger:
  baud_rate: 0

web_server:
  port: 80
  auth:
    username: admin
    password: !secret ota_api_password

globals:
  # 0=closed, 1=opening, 2=open, 3=closing
  - id: gate_state
    type: int
    restore_value: yes
    initial_value: '0'

binary_sensor:
  - platform: gpio
    name: "Driveway Swing Gate Controller Button"
    internal: true
    pin:
      number: GPIO0
      inverted: True
    on_click:
      then:
        - switch.toggle: driveway_swing_gate_relay
  - platform: gpio
    name: "Driveway Swing Gate Moving Sensor"
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    on_state:
      then:
        - lambda: |-
            id(gate_state) = (id(gate_state) + 1) % 4;
            auto state = id(gate_state);
            auto swing_gate = id(driveway_swing_gate);
            if (state == 0) {
              swing_gate->position = COVER_CLOSED;
              swing_gate->publish_state();
            }
            else if (state == 1) {
              auto call = swing_gate->make_call();
              call.set_command_open();
              call.perform();
            }
            else if (state == 2) {
              swing_gate->position = COVER_OPEN;
              swing_gate->publish_state();
            }
            else if (state == 3) {
              auto call = swing_gate->make_call();
              call.set_command_close();
              call.perform();
            }
  - platform: template
    name: "Driveway Swing Gate Open Sensor"
    id: driveway_swing_gate_open_sensor
    lambda: 'return id(gate_state) == 2;'
  - platform: template
    name: "Driveway Swing Gate Closed Sensor"
    id: driveway_swing_gate_closed_sensor
    lambda: 'return id(gate_state) == 0;'

cover:
  - platform: endstop
    device_class: gate
    id: driveway_swing_gate
    name: "Driveway Swing Gate"
    open_action:
      - switch.turn_on: driveway_swing_gate_open_switch
    open_duration: 27s
    open_endstop: driveway_swing_gate_open_sensor

    close_action:
      - switch.turn_on: driveway_swing_gate_close_switch
    close_duration: 27s
    close_endstop: driveway_swing_gate_closed_sensor

    stop_action:
      - switch.turn_on: driveway_swing_gate_stop_switch
      
switch:
  - platform: restart
    name: "Reboot Driveway Swing Gate Controller"
    id: driveway_swing_gate_controller_restart
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin: 
      number: D1
      inverted: False
    name: "Driveway Swing Gate Internal Relay Switch"
    id: internal_relay_switch
    internal: True
  - platform: template
    restore_mode: ALWAYS_OFF
    name: "Driveway Swing Gate Relay"
    id: driveway_swing_gate_relay
    turn_on_action:
      - switch.turn_on: internal_relay_switch
      - delay: 250ms
      - switch.turn_off: internal_relay_switch
      - switch.turn_off: driveway_swing_gate_relay
  - platform: template
    restore_mode: ALWAYS_OFF
    name: "Driveway Swing Gate Open Switch"
    id: driveway_swing_gate_open_switch
    turn_on_action:
      - if:
          condition:
            lambda: 'return id(gate_state) == 0;'
          then:
            - logger.log: "Open Switch: Gate is closed, opening..."
            - switch.turn_on: driveway_swing_gate_relay
      - delay: 2s
      - switch.turn_off: driveway_swing_gate_open_switch
  - platform: template
    restore_mode: ALWAYS_OFF
    name: "Driveway Swing Gate Close Switch"
    id: driveway_swing_gate_close_switch
    turn_on_action:
      - if:
          condition:
            lambda: 'return id(gate_state) == 2;'
          then:
            - logger.log: "Close Switch: Gate is open, closing..."
            - switch.turn_on: driveway_swing_gate_relay
      - delay: 2s
      - switch.turn_off: driveway_swing_gate_close_switch
  - platform: template
    restore_mode: ALWAYS_OFF
    name: "Driveway Swing Gate Stop Switch"
    id: driveway_swing_gate_stop_switch
    turn_on_action:
      - if:
          condition:
            lambda: 'return id(gate_state) % 2 == 1;'
          then:
            - logger.log: "Stop Switch: Gate is moving, stopping..."
            - switch.turn_on: driveway_swing_gate_relay
      - delay: 2s
      - switch.turn_off: driveway_swing_gate_stop_switch
  - platform: template
    restore_mode: ALWAYS_OFF
    name: "Driveway Swing Gate State Reset to Closed"
    id: driveway_swing_gate_state_reset
    turn_on_action:
      - globals.set:
          id: gate_state
          value: '0'
      - lambda: |-
          if (id(gate_state) == 0) {
            id(driveway_swing_gate)->position = COVER_CLOSED;
            id(driveway_swing_gate).publish_state();
          }
      - switch.turn_off: driveway_swing_gate_state_reset
