esphome:
  name: driveway_swing_gate_controller
  platform: ESP8266
  board: WEMOS
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  ap:
    ssid: "driveway_swing_gate_controller"
    password: "esphome1"
  domain: .twohunnid
  fast_connect: true

# Enable logging
logger:
  baud_rate: 0

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    name: "Driveway Swing Gate Controller Button"
    internal: true
    pin:
      number: GPIO0
      inverted: True
    on_click:
      then:
        - switch.toggle: driveway_swing_gate_relay
  - platform: gpio
    name: "Driveway Swing Gate Controller Closed Sensor"
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    name: "Driveway Swing Gate Controller Open Sensor"
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
      
switch:
  - platform: restart
    name: "Reboot Driveway Swing Gate Controller"
    id: driveway_swing_gate_controller_restart
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin: 
      number: D1
      inverted: False
    name: "Driveway Swing Gate Internal Relay Switch"
    id: internal_relay_switch
    internal: True
  - platform: template
    name: "Driveway Swing Gate Relay"
    id: driveway_swing_gate_relay
    turn_on_action:
      - switch.turn_on: internal_relay_switch
      - delay: 250ms
      - switch.turn_off: internal_relay_switch
      - switch.turn_off: driveway_swing_gate_relay

# Enable Home Assistant API
api:
  password: !secret ota_api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_api_password
