esphome:
  name: driveway_swing_gate_controller
  platform: ESP8266
  board: d1_mini_pro
  board_flash_mode: dout
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  ap:
    ssid: "driveway_swing_gate_controller"
    password: "esphome1"
  domain: .twohunnid
  fast_connect: true

# Enable logging
logger:
  baud_rate: 0

web_server:
  port: 80

globals:
  # 0=closed, 1=opening, 2=open, 3=closing
  - id: gate_state
    type: int
    restore_value: yes
    initial_value: '0'

binary_sensor:
  - platform: gpio
    name: "Driveway Swing Gate Controller Button"
    internal: true
    pin:
      number: GPIO0
      inverted: True
    on_click:
      then:
        - switch.toggle: driveway_swing_gate_relay
  - platform: gpio
    name: "Driveway Swing Gate Moving Sensor"
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    on_state:
      then:
        - lambda: |-
            id(gate_state) = (id(gate_state) + 1) % 4;
            if (id(gate_state) == 0) {
              id(driveway_swing_gate).publish_state(COVER_CLOSED)
            }
            if (id(gate_state) == 2) {
              id(driveway_swing_gate).publish_state(COVER_OPEN)
            }
  - platform: template
    name: "Driveway Swing Gate Open Sensor"
    id: driveway_swing_gate_open_sensor
    lambda: 'return id(gate_state) == 2;'
  - platform: template
    name: "Driveway Swing Gate Closed Sensor"
    id: driveway_swing_gate_closed_sensor
    lambda: 'return id(gate_state) == 0;'

cover:
  - platform: endstop
    device_class: gate
    id: driveway_swing_gate
    name: "Driveway Swing Gate"
    open_action:
      - switch.turn_on: driveway_swing_gate_relay
    open_duration: 27s
    open_endstop: driveway_swing_gate_open_sensor

    close_action:
      - switch.turn_on: driveway_swing_gate_relay
    close_duration: 27s
    close_endstop: driveway_swing_gate_closed_sensor

    stop_action:
      - if:
          condition:
            lambda: 'return id(gate_state) % 2 == 1;'
          then:
            - switch.turn_on: driveway_swing_gate_relay
      
switch:
  - platform: restart
    name: "Reboot Driveway Swing Gate Controller"
    id: driveway_swing_gate_controller_restart
  - platform: gpio
    restore_mode: ALWAYS_OFF
    pin: 
      number: D1
      inverted: False
    name: "Driveway Swing Gate Internal Relay Switch"
    id: internal_relay_switch
    internal: True
  - platform: template
    restore_state: false
    name: "Driveway Swing Gate Relay"
    id: driveway_swing_gate_relay
    turn_on_action:
      - switch.turn_on: internal_relay_switch
      - delay: 250ms
      - switch.turn_off: internal_relay_switch
      - switch.turn_off: driveway_swing_gate_relay
  - platform: template
    restore_state: false
    name: "Driveway Swing Gate State Reset to Closed"
    id: driveway_swing_gate_state_reset
    turn_on_action:
      - globals.set:
          id: gate_state
          value: '0'
      - lambda: |-
          if (id(gate_state) == 0) {
            id(driveway_swing_gate).publish_state(COVER_CLOSED)
          }
      - switch.turn_off: driveway_swing_gate_state_reset

# Enable Home Assistant API
api:
  password: !secret ota_api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_api_password
