substitutions:
  device_name: kitchen_sconces

esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m
  board_flash_mode: dout

wifi:
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_primary_ssid
    password: !secret wifi_primary_password
  - ssid: !secret wifi_secondary_ssid
    password: !secret wifi_secondary_password
  ap:
    ssid: ${device_name}_AP

captive_portal:

api:
  encryption:
    key: lAgRmgEOUxjseWPg8t+Z+Y6VKUPnhKzL9olhA1JS8Io=
  reboot_timeout: 0s

ota:
  - platform: esphome
    id: ha_ota
    password: !secret ota_api_password

# Enable logging
logger:
  
output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True
  - platform: gpio
    pin: GPIO12
    id: main_relay
    
switch:
  - platform: restart
    name: "Reboot Kitchen Sconce Sonoff"
    id: kitchen_sconces_restart

light:
  - platform: monochromatic
    name: "Sonoff Basic Green LED"
    output: basic_green_led
  - platform: binary
    name: "Kitchen Sconces"
    id: kitchen_sconces
    output: main_relay
    
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: True
    name: "Kitchen Sconce Physical Switch Sensor"
    on_press:
      then:
        - light.toggle: kitchen_sconces
    on_release:
      then:
        - light.toggle: kitchen_sconces
    on_multi_click:
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 0.2s
      then:
        - switch.turn_on: kitchen_sconces_restart
