substitutions:
  device_index: "01"
  device_name: linknode_r4
  friendly_name: Linknode R4

esphome:
  name: ${device_name}_${device_index}
  platform: ESP8266
  board: esp12e

wifi:
  networks:
  - ssid: !secret wifi_primary_ssid
    password: !secret wifi_primary_password
  - ssid: !secret wifi_secondary_ssid
    password: !secret wifi_secondary_password
  ap:
    ssid: ${device_name}_${device_index}_config
    password: !secret ap_password

logger:
  baud_rate: 0

web_server:
  port: 80
  auth:
    username: admin
    password: !secret ota_api_password

ota:
  password: !secret ota_api_password

api:
  password: !secret ota_api_password

sensor:
  - platform: uptime
    name: "${friendly_name} ${device_index} Uptime"
    id: uptime_seconds
  - platform: wifi_signal
    name: "${friendly_name} ${device_index} WiFi Signal"

# Use the blue LED in the device as a status LED, which will blink if there are warnings (slow) or errors (fast)
status_led:
  pin:
    number: GPIO5
    inverted: True

switch:
  - platform: gpio
    pin: GPIO16
    name: ${friendly_name} ${device_index} Relay 1
    id: relay1
  - platform: gpio
    pin: GPIO14
    name: ${friendly_name} ${device_index} Relay 2
    id: relay2
  - platform: gpio
    pin: GPIO12
    name: ${friendly_name} ${device_index} Relay 3
    id: relay3
  - platform: gpio
    pin: GPIO13
    name: ${friendly_name} ${device_index} Relay 4
    id: relay4