substitutions:
  device_name: northern_string_lights

esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m
  board_flash_mode: dout

wifi:
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_primary_ssid
    password: !secret wifi_primary_password
  - ssid: !secret wifi_secondary_ssid
    password: !secret wifi_secondary_password
  ap:
    ssid: ${device_name}_AP

captive_portal:

# Enable logging
logger:
  
output:
  - platform: gpio
    pin: GPIO12
    id: main_relay
    
switch:
  - platform: restart
    name: "Reboot Northern String Lights Sonoff"
    id: northern_string_lights_restart

light:
  - platform: binary
    name: "Northern String Lights"
    id: northern_string_lights
    output: main_relay
    
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: True
    name: "Northern String Lights Physical Switch Sensor"
    on_press:
      then:
        - light.toggle: northern_string_lights
    on_release:
      then:
        - light.toggle: northern_string_lights
    on_multi_click:
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at most 0.5s
        - ON for at most 0.5s
        - OFF for at least 0.2s
      then:
        - switch.turn_on: northern_string_lights_restart
        
# Enable Home Assistant API
api:
  encryption:
    key: F4IWJMqLkJxEfuKeLNdy7+7q3Ze9+EPTAliTEOArv+Y=
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_api_password
