esphome:
  name: pool_pump
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  domain: .twohunnid
  fast_connect: true

logger:
  baud_rate: 0

web_server:
  port: 80
  auth:
    username: admin
    password: !secret ota_api_password
  
output:

  - platform: esp8266_pwm
    id: basic_blue_led
    pin:
      number: GPIO13
      inverted: True
      
  - platform: gpio
    pin: GPIO12
    id: main_relay
    
    
light:
  - platform: monochromatic
    id: blue_status_light
    internal: True
    output: basic_blue_led

switch:
  - platform: restart
    name: "Reboot Pool Pump Sonoff"
    id: pool_pump_restart
    
  - platform: output
    name: "Pool Pump"
    id: pool_pump
    output: main_relay

interval:
  - interval: 3s
    then:
      if:
        condition:
          not:
            wifi.connected:
        then:
          - light.toggle: 
              id: blue_status_light
              transition_length: 0s
          - delay: 200ms
          - light.toggle: 
              id: blue_status_light
              transition_length: 0s
          - delay: 200ms
          - light.toggle: 
              id: blue_status_light
              transition_length: 0s
          - delay: 200ms
          - light.toggle: 
              id: blue_status_light
              transition_length: 0s

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy 
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Pool Pump IP Address
      entity_category: "diagnostic"
    ssid:
      name: Pool Pump Connected SSID
      entity_category: "diagnostic"
    scan_results:
      name: Pool Pump Latest Scan Results
      entity_category: "diagnostic"
    
binary_sensor:

  - platform: gpio
    pin: 
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    name: "Pool Pump Timer Physical Timer"
    on_press:
      then:
        - switch.turn_on: pool_pump
        - light.turn_on: 
            id: blue_status_light
            transition_length: 0s
    on_release:
      then:
        - switch.turn_off: pool_pump
        - light.turn_off: 
            id: blue_status_light
            transition_length: 0s
        
  - platform: gpio
    internal: true
    id: sonoff_button
    pin: 
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_release:
      then:
        - switch.toggle: pool_pump
    on_multi_click:
    - timing:
        - ON for at least 10s
        - OFF for at most 0.5s
      then:
        - switch.turn_on: pool_pump_restart
        
# Enable Home Assistant API
api:
  password: !secret ota_api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_api_password
