substitutions:
  device_index: "03"
  device_name: sonoff_mini
  friendly_name: Sonoff Mini

# GPIO0 Button (inverted)
# GPIO4 SW Input (inverted)
# GPIO12 Relay and Red LED
# GPIO13 Blue LED (inverted)
# GPIO16 Optional sensor

esphome:
  name: ${device_name}_${device_index}

esp8266:
  board: esp01_1m

wifi:
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_primary_ssid
    password: !secret wifi_primary_password
  - ssid: !secret wifi_secondary_ssid
    password: !secret wifi_secondary_password
  ap:
    ssid: ${device_name}_AP

captive_portal:

api:
  encryption:
    key: imji7mPxqXaBaVTT9pdKqqM8zekJvab7Qkw2Ju+9uCM=
  reboot_timeout: 0s

ota:
  - platform: esphome
    id: ha_ota
    password: !secret ota_api_password

logger:
  baud_rate: 0

web_server:
  port: 80
  auth:
    username: admin
    password: !secret ota_api_password

output:
- platform: gpio
  id: gpio_13
  inverted: True
  pin: GPIO13

light:
- platform: binary
  id: power_led
  name: "${friendly_name} ${device_index} Power LED"
  output: gpio_13
  effects:
    - strobe:
  
switch:
  - platform: gpio
    name: "${friendly_name} ${device_index}"
    icon: mdi:power-socket-us
    id: relay1
    pin:
      number: GPIO12
      inverted: False
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - light.turn_on: power_led
    on_turn_off:
    - light.turn_off: power_led

  - platform: restart
    name: "Reboot ${friendly_name} ${device_index}"
    id: reboot
    
binary_sensor:
  - platform: gpio
    id: power_button
    pin: 
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_release:
      then:
        - switch.toggle: relay1
  - platform: gpio
    id: power_switch
    pin: 
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      then:
        - switch.toggle: relay1
    on_release:
      then:
        - switch.toggle: relay1
