homeassistant:
  customize:
    group.climate:
      order: 40
      
group:
  climate:
    
    name: Climate & Temperature
    icon: mdi:thermostat
    entities:
      - history_graph.temperature
      - climate.dining_room
      - climate.hallway
      
history_graph:
  temperature:
    entities:
      - sensor.dining_room_thermostat_temperature
      - sensor.hallway_thermostat_temperature
      - sensor.dark_sky_temperature
    hours_to_show: 120
    refresh: 60