homeassistant:
  customize:
    group.configuration:
      order: 90
      
group:
  configuration:
    name: Config
    icon: mdi:cogs
    
    entities:
      - group.home_settings
      - group.hahardware
      - group.hardware_freenas
      - group.ha_control
      - group.battery_status

  hardware_freenas:
    
    entities:
      - sensor.freenas_version
      - sensor.freenas_alert_level
      - sensor.freenas_alert_message
      - sensor.freenas_tank_report
      - sensor.freenas_tank_pct_used
      - sensor.freenas_resilver_etc
      
  home_settings:
    name: Home Settings
    
    
    entities:
      - input_boolean.dogs_home
      - switch.edmond_is_outside
      - input_boolean.vacation_mode
      - group.holiday_modes
      
  holiday_modes:
    name: Holiday Modes
    
    
    entities:
      - input_boolean.halloween_mode
      - input_boolean.christmas_mode
      
  hahardware:
    name: HomeAssistant Hardware
    
    entities:
      - sensor.disk_use_percent_home
      - sensor.memory_use_percent
      - sensor.load_5m
      - sensor.last_boot
      
  ha_control:
    name: HA Control
    
    
    entities:
      - script.git_pull
      - script.homeassistant_reload_without_restart
      - script.homeassistant_restart