homeassistant:
  customize:
    group.door_window_motion_sound_sensors:
      order: 70
      
group:
  door_window_motion_sound_sensors:
    view: yes
    name: Doors, Windows, Motion and Sound
    icon: mdi:eye
    entities:
      - group.all_exterior_motion_sensors
      - group.all_interior_motion_sensors
      - group.all_doors
      - group.motion_sensor_scripts