homeassistant:
  customize:
    group.default_view:
      order: 10

group:
  default_view:
    icon: mdi:home-heart
    
    name: Favorites
    entities:
      - group.alarm_arming
      - group.favorite_locks
      - group.favorite_lights
      - group.favorite_switches
      - group.pool
      
  favorite_locks:
    
    icon: mdi:lock
    name: Doors & Locks
    entities:
      - lock.kwikset_touchpad_electronic_deadbolt_locked
      - lock.kwikset_touchpad_electronic_deadbolt_locked_2
      - cover.garage_door
  
  favorite_lights:
    
    icon: mdi:lightbulb
    name: Lights
    entities:
      - light.leviton_dzmx1_1lz_dimmer_level
      - light.zwaveproducts_com_wd_100_level
      - light.string_lights
      
  favorite_switches:
    
    icon: mdi:switch
    name: Switches
    entities:
      - switch.pool_pump