homeassistant:
  customize:
    group.default_view:
      order: 1

group:
  default_view:
    icon: mdi:heart
    view: yes
    name: Favorites
    entities:
      - group.alarm_arming
      - group.favorite_locks
      - group.favorite_lights
      - group.favorite_switches
      
  favorite_locks:
    control: hidden
    icon: mdi:lock
    name: Doors & Locks
    entities:
      - lock.kwikset_touchpad_electronic_deadbolt_locked
      - lock.kwikset_touchpad_electronic_deadbolt_locked_2
  
  favorite_lights:
    control: hidden
    icon: mdi:lightbulb
    name: Lights
    entities:
      - light.leviton_dzmx11lz_dimmer_level
      - light.string_lights
      
  favorite_switches:
    control: hidden
    icon: mdi:switch
    name: Switches
    entities:
      - switch.garage_door_button