homeassistant:
  customize:
    group.health:
      order: 80

group:
  health:
    icon: mdi:heart-pulse
    
    name: Health
    entities:
      - group.health_zwift
      - group.health_nick
      
  health_nick:
    
    icon: mdi:account
    name: Health - Nick
    entities:
      - sensor.weightgurus_nick