homeassistant:
  customize:
    group.lights_and_locks:
      order: 20
    group.all_locks:
      hidden: false
      
group:
  lights_and_locks:
    
    name: Lights, Locks, and Switches
    icon: mdi:lightbulb
    entities:
      - group.interior_lights
      - group.exterior_lights
      - group.switches
      - group.all_locks