homeassistant:
  customize:
    group.media_players:
      order: 50
      
group:
  media_players:
    view: yes
    name: Media Players
    icon: mdi:movie
    entities:
      - media_player.universal_media_player_living_room
      - media_player.living_room_fire_tv
      - media_player.spotify
      - media_player.master_bedroom_fire_tv
      - media_player.master_bedroom_television