################################################################
## Packages / plant_ui
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_ui'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
     
    group.plants:
      <<: *customize
      friendly_name: Plants
      icon: mdi:flower
      order: 75
     
    history_graph.plant_moisture:
      <<: *customize
      friendly_name: Plants - Moisture
      
    script.plantgateway_update:
      <<: *customize
      friendly_name: Force Plantgateway Update
      alias: Force Plantgateway Update
    
    automation.local_plant_gateway:
      <<: *customize
      friendly_name: Execute local Plantgateway every 15 minutes
    
group:
  plants:
    name: Plants
    
    entities:
      - plant.desert_rose
      - plant.zebra_plant
      - plant.peace_lily
      - plant.fiddle_leaf_fig
      - plant.dragon_tree