homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'backyard_amplifier'
        
    light.outside_amplifier_28:
      <<: *customize
      hidden: true
    
    switch.backyard_amplifier:
      <<: *customize
      friendly_name: "Backyard Amplifier"
      comm_protocol: "infrared"
      
    automation.backyard_amplifier_auto_on:
      <<: *customize
      friendly_name: "Backyard Amplifier: Auto On"
      
    automation.backyard_amplifier_auto_off:
      <<: *customize
      friendly_name: "Backyard Amplifier: Auto Off"

switch:
  - platform: template
    switches:
      backyard_amplifier:
        value_template: "{{ is_state('switch.25048234840d8ebe302f', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.25048234840d8ebe302f
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.25048234840d8ebe302f
            
automation:
  - id: backyard_amplifier_auto_on
    alias: backyard_amplifier_auto_on
    trigger:
    - entity_id: media_player.backyard_dot
      platform: state
      to: playing
    - entity_id: sensor.last_alexa
      platform: state
      to: media_player.backyard_dot
    condition: []
    action:
    - data:
        entity_id: switch.backyard_amplifier
      service: switch.turn_on
  - id: backyard_amplifier_auto_off
    alias: backyard_amplifier_auto_off
    trigger:
    - platform: state
      entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
      to: locked
    - platform: template
      value_template: "{{ states('media_player.backyard_dot') != 'playing' }}"
      for: "00:05:00"
    - platform: template
      value_template: "{{ states('sensor.last_alexa') != 'media_player.backyard_dot' and states('media_player.backyard_dot') != 'playing' }}"
      for: "00:05:00"
    condition: []
    action:
    - data:
        entity_id: switch.backyard_amplifier
      service: switch.turn_off