homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'backyard_amplifier'
        
    light.outside_amplifier_28:
      <<: *customize
      hidden: true
    
    switch.backyard_amplifier:
      <<: *customize
      friendly_name: "Backyard Amplifier"
      comm_protocol: "infrared"

switch:
  - platform: template
    switches:
      backyard_amplifier:
        value_template: "{{ is_state('light.outside_amplifier_28', 'on') }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.outside_amplifier_28
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.outside_amplifier_28
            
automation:
  - alias: backyard_amplifier_auto_on
    trigger:
      - platform: state
        entity_id:
          - media_player.backyard_dot
        to: "playing"
      - platform: state
        entity_id:
          - sensor.last_alexa
        to: "media_player.backyard_dot"
    condition: []
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.backyard_amplifier
  - alias: backyard_amplifier_auto_on
    trigger:
      - platform: state
        entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
        to: "locked"
      - platform: template
        entity_id:
          - media_player.backyard_dot
        value_template: "{{ states('media_player.backyard_dot') != 'playing' }}"
        for: "00:05:00"
      - platform: template
        entity_id:
          - sensor.last_alexa
          - media_player.backyard_dot
        value_template: "{{ states('sensor.last_alexa') != 'media_player.backyard_dot' and states('media_player.backyard_dot') != 'playing' }}"
        for: "00:05:00"
    condition: []
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.backyard_amplifier
