homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'proximity_nick'
        
    proximity.nick_home:
      <<: *customize
      friendly_name: "Proximity: Nick to Home"
      
    sensor.travel_time_nick_to_home:
      <<: *customize
      friendly_name: "Travel Time: Nick to Home"
        
proximity:
  nick_home:
    zone: home
    devices:
      - device_tracker.nickcell
      - device_tracker.life360_nick
    tolerance: 50
    unit_of_measurement: mi

sensor:    
  - platform: waze_travel_time
    name: travel_time_nick_to_home
    origin: device_tracker.life360_nick
    destination: zone.home
    region: 'US'
  