homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'proximity_nick'
      
    sensor.travel_time_nick_to_home_eta:
      <<: *customize
      friendly_name: "Travel Time: Nick to Home ETA"

template:    
  - sensor:
      - name: travel_time_nick_to_home_eta
        state: >-
          {% set last_updated = as_timestamp(states.sensor.nick_to_home_travel_time.last_updated) | float %}
          {% set time_to_dest = states('sensor.nick_to_home_travel_time') | float * 60 %}
          {{ (last_updated + time_to_dest) | timestamp_custom() }}